//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmbitoValidezCIE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmbitoValidezCIE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="AU"/>
 *     &lt;enumeration value="PR"/>
 *     &lt;enumeration value="LO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AmbitoValidezCIE")
@XmlEnum
public enum AmbitoValidezCIE {

    ES,
    AU,
    PR,
    LO;

    public String value() {
        return name();
    }

    public static AmbitoValidezCIE fromValue(String v) {
        return valueOf(v);
    }

}
