//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Anomalia complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Anomalia">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodAnomalia" type="{http://localhost/elegibilidad}TipoAnomalia"/>
 *         &lt;element name="Descripcion" type="{http://localhost/elegibilidad}X45"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anomalia", propOrder = {
    "codAnomalia",
    "descripcion"
})
public class Anomalia {

    @XmlElement(name = "CodAnomalia", required = true)
    protected TipoAnomalia codAnomalia;
    @XmlElement(name = "Descripcion", required = true)
    protected String descripcion;

    /**
     * Gets the value of the codAnomalia property.
     * 
     * @return
     *     possible object is
     *     {@link TipoAnomalia }
     *     
     */
    public TipoAnomalia getCodAnomalia() {
        return codAnomalia;
    }

    /**
     * Sets the value of the codAnomalia property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoAnomalia }
     *     
     */
    public void setCodAnomalia(TipoAnomalia value) {
        this.codAnomalia = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

}
