//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Aparato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Aparato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Modelo" type="{http://localhost/elegibilidad}ModeloAparato"/>
 *         &lt;element name="TipoMovimiento" type="{http://localhost/elegibilidad}TipoMovimiento"/>
 *         &lt;element name="TipoEquipoMedida" type="{http://localhost/elegibilidad}TiposEquipoMedida"/>
 *         &lt;element name="TipoPropiedadAparato" type="{http://localhost/elegibilidad}TipoPropiedadAparato"/>
 *         &lt;element name="Propietario" type="{http://localhost/elegibilidad}X20" minOccurs="0"/>
 *         &lt;element name="ExtraccionLecturas" type="{http://localhost/elegibilidad}Indicativo" minOccurs="0"/>
 *         &lt;element name="DiscriminacionHorariaActiva" type="{http://localhost/elegibilidad}TipoDHActiva" minOccurs="0"/>
 *         &lt;element name="DiscriminacionHorariaMaximas" type="{http://localhost/elegibilidad}TipoDHMaximas" minOccurs="0"/>
 *         &lt;element name="LecturaDirecta" type="{http://localhost/elegibilidad}Indicativo" minOccurs="0"/>
 *         &lt;element name="CodPrecinto">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="DatosAparatoNoICP" type="{http://localhost/elegibilidad}DatosAparatoNoICP"/>
 *           &lt;element name="DatosAparatoICP" type="{http://localhost/elegibilidad}DatosAparatoICP"/>
 *         &lt;/choice>
 *         &lt;element name="Medidas" type="{http://localhost/elegibilidad}MedidasAparato" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Aparato", propOrder = {
    "modelo",
    "tipoMovimiento",
    "tipoEquipoMedida",
    "tipoPropiedadAparato",
    "propietario",
    "extraccionLecturas",
    "discriminacionHorariaActiva",
    "discriminacionHorariaMaximas",
    "lecturaDirecta",
    "codPrecinto",
    "datosAparatoNoICP",
    "datosAparatoICP",
    "medidas"
})
public class Aparato {

    @XmlElement(name = "Modelo", required = true)
    protected ModeloAparato modelo;
    @XmlElement(name = "TipoMovimiento", required = true)
    protected TipoMovimiento tipoMovimiento;
    @XmlElement(name = "TipoEquipoMedida", required = true)
    protected TiposEquipoMedida tipoEquipoMedida;
    @XmlElement(name = "TipoPropiedadAparato", required = true)
    protected String tipoPropiedadAparato;
    @XmlElement(name = "Propietario")
    protected String propietario;
    @XmlElement(name = "ExtraccionLecturas")
    protected String extraccionLecturas;
    @XmlElement(name = "DiscriminacionHorariaActiva")
    protected String discriminacionHorariaActiva;
    @XmlElement(name = "DiscriminacionHorariaMaximas")
    protected String discriminacionHorariaMaximas;
    @XmlElement(name = "LecturaDirecta")
    protected String lecturaDirecta;
    @XmlElement(name = "CodPrecinto", required = true)
    protected String codPrecinto;
    @XmlElement(name = "DatosAparatoNoICP")
    protected DatosAparatoNoICP datosAparatoNoICP;
    @XmlElement(name = "DatosAparatoICP")
    protected DatosAparatoICP datosAparatoICP;
    @XmlElement(name = "Medidas")
    protected MedidasAparato medidas;

    /**
     * Gets the value of the modelo property.
     * 
     * @return
     *     possible object is
     *     {@link ModeloAparato }
     *     
     */
    public ModeloAparato getModelo() {
        return modelo;
    }

    /**
     * Sets the value of the modelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModeloAparato }
     *     
     */
    public void setModelo(ModeloAparato value) {
        this.modelo = value;
    }

    /**
     * Gets the value of the tipoMovimiento property.
     * 
     * @return
     *     possible object is
     *     {@link TipoMovimiento }
     *     
     */
    public TipoMovimiento getTipoMovimiento() {
        return tipoMovimiento;
    }

    /**
     * Sets the value of the tipoMovimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoMovimiento }
     *     
     */
    public void setTipoMovimiento(TipoMovimiento value) {
        this.tipoMovimiento = value;
    }

    /**
     * Gets the value of the tipoEquipoMedida property.
     * 
     * @return
     *     possible object is
     *     {@link TiposEquipoMedida }
     *     
     */
    public TiposEquipoMedida getTipoEquipoMedida() {
        return tipoEquipoMedida;
    }

    /**
     * Sets the value of the tipoEquipoMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link TiposEquipoMedida }
     *     
     */
    public void setTipoEquipoMedida(TiposEquipoMedida value) {
        this.tipoEquipoMedida = value;
    }

    /**
     * Gets the value of the tipoPropiedadAparato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPropiedadAparato() {
        return tipoPropiedadAparato;
    }

    /**
     * Sets the value of the tipoPropiedadAparato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPropiedadAparato(String value) {
        this.tipoPropiedadAparato = value;
    }

    /**
     * Gets the value of the propietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropietario() {
        return propietario;
    }

    /**
     * Sets the value of the propietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropietario(String value) {
        this.propietario = value;
    }

    /**
     * Gets the value of the extraccionLecturas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraccionLecturas() {
        return extraccionLecturas;
    }

    /**
     * Sets the value of the extraccionLecturas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraccionLecturas(String value) {
        this.extraccionLecturas = value;
    }

    /**
     * Gets the value of the discriminacionHorariaActiva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscriminacionHorariaActiva() {
        return discriminacionHorariaActiva;
    }

    /**
     * Sets the value of the discriminacionHorariaActiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscriminacionHorariaActiva(String value) {
        this.discriminacionHorariaActiva = value;
    }

    /**
     * Gets the value of the discriminacionHorariaMaximas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscriminacionHorariaMaximas() {
        return discriminacionHorariaMaximas;
    }

    /**
     * Sets the value of the discriminacionHorariaMaximas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscriminacionHorariaMaximas(String value) {
        this.discriminacionHorariaMaximas = value;
    }

    /**
     * Gets the value of the lecturaDirecta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLecturaDirecta() {
        return lecturaDirecta;
    }

    /**
     * Sets the value of the lecturaDirecta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLecturaDirecta(String value) {
        this.lecturaDirecta = value;
    }

    /**
     * Gets the value of the codPrecinto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPrecinto() {
        return codPrecinto;
    }

    /**
     * Sets the value of the codPrecinto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPrecinto(String value) {
        this.codPrecinto = value;
    }

    /**
     * Gets the value of the datosAparatoNoICP property.
     * 
     * @return
     *     possible object is
     *     {@link DatosAparatoNoICP }
     *     
     */
    public DatosAparatoNoICP getDatosAparatoNoICP() {
        return datosAparatoNoICP;
    }

    /**
     * Sets the value of the datosAparatoNoICP property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosAparatoNoICP }
     *     
     */
    public void setDatosAparatoNoICP(DatosAparatoNoICP value) {
        this.datosAparatoNoICP = value;
    }

    /**
     * Gets the value of the datosAparatoICP property.
     * 
     * @return
     *     possible object is
     *     {@link DatosAparatoICP }
     *     
     */
    public DatosAparatoICP getDatosAparatoICP() {
        return datosAparatoICP;
    }

    /**
     * Sets the value of the datosAparatoICP property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosAparatoICP }
     *     
     */
    public void setDatosAparatoICP(DatosAparatoICP value) {
        this.datosAparatoICP = value;
    }

    /**
     * Gets the value of the medidas property.
     * 
     * @return
     *     possible object is
     *     {@link MedidasAparato }
     *     
     */
    public MedidasAparato getMedidas() {
        return medidas;
    }

    /**
     * Sets the value of the medidas property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedidasAparato }
     *     
     */
    public void setMedidas(MedidasAparato value) {
        this.medidas = value;
    }

}
