//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Cabecera complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cabecera">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoREEEmpresaEmisora" type="{http://localhost/elegibilidad}Agente"/>
 *         &lt;element name="CodigoREEEmpresaDestino" type="{http://localhost/elegibilidad}Agente"/>
 *         &lt;element name="CodigoDelProceso" type="{http://localhost/elegibilidad}CodigoDelProceso"/>
 *         &lt;element name="CodigoDePaso" type="{http://localhost/elegibilidad}CodigoDePaso"/>
 *         &lt;element name="CodigoDeSolicitud" type="{http://localhost/elegibilidad}CodigoDeSolicitud"/>
 *         &lt;element name="SecuencialDeSolicitud" type="{http://localhost/elegibilidad}SecuencialDeSolicitud"/>
 *         &lt;element name="Codigo" type="{http://localhost/elegibilidad}Codigo"/>
 *         &lt;element name="FechaSolicitud" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Version" type="{http://localhost/elegibilidad}Version"/>
 *         &lt;element name="CodigoDeError" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cabecera", propOrder = {
    "codigoREEEmpresaEmisora",
    "codigoREEEmpresaDestino",
    "codigoDelProceso",
    "codigoDePaso",
    "codigoDeSolicitud",
    "secuencialDeSolicitud",
    "codigo",
    "fechaSolicitud",
    "version",
    "codigoDeError"
})
public class Cabecera {

    @XmlElement(name = "CodigoREEEmpresaEmisora", required = true)
    protected String codigoREEEmpresaEmisora;
    @XmlElement(name = "CodigoREEEmpresaDestino", required = true)
    protected String codigoREEEmpresaDestino;
    @XmlElement(name = "CodigoDelProceso", required = true)
    protected String codigoDelProceso;
    @XmlElement(name = "CodigoDePaso", required = true)
    protected String codigoDePaso;
    @XmlElement(name = "CodigoDeSolicitud", required = true)
    protected String codigoDeSolicitud;
    @XmlElement(name = "SecuencialDeSolicitud", required = true)
    protected String secuencialDeSolicitud;
    @XmlElement(name = "Codigo", required = true)
    protected String codigo;
    @XmlElement(name = "FechaSolicitud", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaSolicitud;
    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "CodigoDeError")
    protected String codigoDeError;

    /**
     * Gets the value of the codigoREEEmpresaEmisora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoREEEmpresaEmisora() {
        return codigoREEEmpresaEmisora;
    }

    /**
     * Sets the value of the codigoREEEmpresaEmisora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoREEEmpresaEmisora(String value) {
        this.codigoREEEmpresaEmisora = value;
    }

    /**
     * Gets the value of the codigoREEEmpresaDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoREEEmpresaDestino() {
        return codigoREEEmpresaDestino;
    }

    /**
     * Sets the value of the codigoREEEmpresaDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoREEEmpresaDestino(String value) {
        this.codigoREEEmpresaDestino = value;
    }

    /**
     * Gets the value of the codigoDelProceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDelProceso() {
        return codigoDelProceso;
    }

    /**
     * Sets the value of the codigoDelProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDelProceso(String value) {
        this.codigoDelProceso = value;
    }

    /**
     * Gets the value of the codigoDePaso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDePaso() {
        return codigoDePaso;
    }

    /**
     * Sets the value of the codigoDePaso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDePaso(String value) {
        this.codigoDePaso = value;
    }

    /**
     * Gets the value of the codigoDeSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDeSolicitud() {
        return codigoDeSolicitud;
    }

    /**
     * Sets the value of the codigoDeSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDeSolicitud(String value) {
        this.codigoDeSolicitud = value;
    }

    /**
     * Gets the value of the secuencialDeSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuencialDeSolicitud() {
        return secuencialDeSolicitud;
    }

    /**
     * Sets the value of the secuencialDeSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuencialDeSolicitud(String value) {
        this.secuencialDeSolicitud = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the fechaSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaSolicitud() {
        return fechaSolicitud;
    }

    /**
     * Sets the value of the fechaSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaSolicitud(XMLGregorianCalendar value) {
        this.fechaSolicitud = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the codigoDeError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDeError() {
        return codigoDeError;
    }

    /**
     * Sets the value of the codigoDeError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDeError(String value) {
        this.codigoDeError = value;
    }

}
