//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIEElectronico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIEElectronico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoCie" type="{http://localhost/elegibilidad}X35" minOccurs="0"/>
 *         &lt;element name="SelloElectronico" type="{http://localhost/elegibilidad}X30" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIEElectronico", propOrder = {
    "codigoCie",
    "selloElectronico"
})
public class CIEElectronico {

    @XmlElement(name = "CodigoCie")
    protected String codigoCie;
    @XmlElement(name = "SelloElectronico")
    protected String selloElectronico;

    /**
     * Gets the value of the codigoCie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCie() {
        return codigoCie;
    }

    /**
     * Sets the value of the codigoCie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCie(String value) {
        this.codigoCie = value;
    }

    /**
     * Gets the value of the selloElectronico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelloElectronico() {
        return selloElectronico;
    }

    /**
     * Sets the value of the selloElectronico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelloElectronico(String value) {
        this.selloElectronico = value;
    }

}
