//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CIEPapel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIEPapel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoCie" type="{http://localhost/elegibilidad}X35"/>
 *         &lt;element name="PotenciaInstBT" type="{http://localhost/elegibilidad}Decimal11"/>
 *         &lt;element name="FechaEmisionCie" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FechaCaducidadCie" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="NifInstalador" type="{http://localhost/elegibilidad}X9"/>
 *           &lt;element name="CodigoInstalador" type="{http://localhost/elegibilidad}X9"/>
 *         &lt;/choice>
 *         &lt;element name="NombreInstalador" type="{http://localhost/elegibilidad}X45"/>
 *         &lt;element name="TensionSuministroCIE" type="{http://localhost/elegibilidad}TensionSuministroCIEyAPM"/>
 *         &lt;element name="IntensidadDif" type="{http://localhost/elegibilidad}X2" minOccurs="0"/>
 *         &lt;element name="SensibilidadDif" type="{http://localhost/elegibilidad}X2" minOccurs="0"/>
 *         &lt;element name="SeccionCable" type="{http://localhost/elegibilidad}X2" minOccurs="0"/>
 *         &lt;element name="TipoSuministro" type="{http://localhost/elegibilidad}TiposSuministro"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIEPapel", propOrder = {
    "codigoCie",
    "potenciaInstBT",
    "fechaEmisionCie",
    "fechaCaducidadCie",
    "nifInstalador",
    "codigoInstalador",
    "nombreInstalador",
    "tensionSuministroCIE",
    "intensidadDif",
    "sensibilidadDif",
    "seccionCable",
    "tipoSuministro"
})
public class CIEPapel {

    @XmlElement(name = "CodigoCie", required = true)
    protected String codigoCie;
    @XmlElement(name = "PotenciaInstBT")
    protected long potenciaInstBT;
    @XmlElement(name = "FechaEmisionCie", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaEmisionCie;
    @XmlElement(name = "FechaCaducidadCie")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaCaducidadCie;
    @XmlElement(name = "NifInstalador")
    protected String nifInstalador;
    @XmlElement(name = "CodigoInstalador")
    protected String codigoInstalador;
    @XmlElement(name = "NombreInstalador", required = true)
    protected String nombreInstalador;
    @XmlElement(name = "TensionSuministroCIE", required = true)
    protected String tensionSuministroCIE;
    @XmlElement(name = "IntensidadDif")
    protected String intensidadDif;
    @XmlElement(name = "SensibilidadDif")
    protected String sensibilidadDif;
    @XmlElement(name = "SeccionCable")
    protected String seccionCable;
    @XmlElement(name = "TipoSuministro", required = true)
    protected TiposSuministro tipoSuministro;

    /**
     * Gets the value of the codigoCie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCie() {
        return codigoCie;
    }

    /**
     * Sets the value of the codigoCie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCie(String value) {
        this.codigoCie = value;
    }

    /**
     * Gets the value of the potenciaInstBT property.
     * 
     */
    public long getPotenciaInstBT() {
        return potenciaInstBT;
    }

    /**
     * Sets the value of the potenciaInstBT property.
     * 
     */
    public void setPotenciaInstBT(long value) {
        this.potenciaInstBT = value;
    }

    /**
     * Gets the value of the fechaEmisionCie property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEmisionCie() {
        return fechaEmisionCie;
    }

    /**
     * Sets the value of the fechaEmisionCie property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEmisionCie(XMLGregorianCalendar value) {
        this.fechaEmisionCie = value;
    }

    /**
     * Gets the value of the fechaCaducidadCie property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaCaducidadCie() {
        return fechaCaducidadCie;
    }

    /**
     * Sets the value of the fechaCaducidadCie property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaCaducidadCie(XMLGregorianCalendar value) {
        this.fechaCaducidadCie = value;
    }

    /**
     * Gets the value of the nifInstalador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNifInstalador() {
        return nifInstalador;
    }

    /**
     * Sets the value of the nifInstalador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNifInstalador(String value) {
        this.nifInstalador = value;
    }

    /**
     * Gets the value of the codigoInstalador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoInstalador() {
        return codigoInstalador;
    }

    /**
     * Sets the value of the codigoInstalador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoInstalador(String value) {
        this.codigoInstalador = value;
    }

    /**
     * Gets the value of the nombreInstalador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreInstalador() {
        return nombreInstalador;
    }

    /**
     * Sets the value of the nombreInstalador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreInstalador(String value) {
        this.nombreInstalador = value;
    }

    /**
     * Gets the value of the tensionSuministroCIE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTensionSuministroCIE() {
        return tensionSuministroCIE;
    }

    /**
     * Sets the value of the tensionSuministroCIE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTensionSuministroCIE(String value) {
        this.tensionSuministroCIE = value;
    }

    /**
     * Gets the value of the intensidadDif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntensidadDif() {
        return intensidadDif;
    }

    /**
     * Sets the value of the intensidadDif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntensidadDif(String value) {
        this.intensidadDif = value;
    }

    /**
     * Gets the value of the sensibilidadDif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensibilidadDif() {
        return sensibilidadDif;
    }

    /**
     * Sets the value of the sensibilidadDif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensibilidadDif(String value) {
        this.sensibilidadDif = value;
    }

    /**
     * Gets the value of the seccionCable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeccionCable() {
        return seccionCable;
    }

    /**
     * Sets the value of the seccionCable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeccionCable(String value) {
        this.seccionCable = value;
    }

    /**
     * Gets the value of the tipoSuministro property.
     * 
     * @return
     *     possible object is
     *     {@link TiposSuministro }
     *     
     */
    public TiposSuministro getTipoSuministro() {
        return tipoSuministro;
    }

    /**
     * Sets the value of the tipoSuministro property.
     * 
     * @param value
     *     allowed object is
     *     {@link TiposSuministro }
     *     
     */
    public void setTipoSuministro(TiposSuministro value) {
        this.tipoSuministro = value;
    }

}
