//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClienteSinTelefono complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClienteSinTelefono">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdCliente" type="{http://localhost/elegibilidad}IdCliente"/>
 *         &lt;element name="Nombre" type="{http://localhost/elegibilidad}NombreCliente"/>
 *         &lt;element name="TitularContratoVsTitularPago" type="{http://localhost/elegibilidad}Indicativo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClienteSinTelefono", propOrder = {
    "idCliente",
    "nombre",
    "titularContratoVsTitularPago"
})
public class ClienteSinTelefono {

    @XmlElement(name = "IdCliente", required = true)
    protected IdCliente idCliente;
    @XmlElement(name = "Nombre", required = true)
    protected NombreCliente nombre;
    @XmlElement(name = "TitularContratoVsTitularPago")
    protected String titularContratoVsTitularPago;

    /**
     * Gets the value of the idCliente property.
     * 
     * @return
     *     possible object is
     *     {@link IdCliente }
     *     
     */
    public IdCliente getIdCliente() {
        return idCliente;
    }

    /**
     * Sets the value of the idCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdCliente }
     *     
     */
    public void setIdCliente(IdCliente value) {
        this.idCliente = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link NombreCliente }
     *     
     */
    public NombreCliente getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link NombreCliente }
     *     
     */
    public void setNombre(NombreCliente value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the titularContratoVsTitularPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitularContratoVsTitularPago() {
        return titularContratoVsTitularPago;
    }

    /**
     * Sets the value of the titularContratoVsTitularPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitularContratoVsTitularPago(String value) {
        this.titularContratoVsTitularPago = value;
    }

}
