//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CondicionesContractualesC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CondicionesContractualesC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TarifaATR" type="{http://localhost/elegibilidad}Tarifa"/>
 *         &lt;element name="PotenciasContratadas" type="{http://localhost/elegibilidad}Potencias"/>
 *         &lt;element name="PotenciasMaximas" type="{http://localhost/elegibilidad}Potencias" minOccurs="0"/>
 *         &lt;element name="ModoControlPotencia" type="{http://localhost/elegibilidad}ModoControlPotencia" minOccurs="0"/>
 *         &lt;element name="MarcaMedidaBTConPerdidas" type="{http://localhost/elegibilidad}X2" minOccurs="0"/>
 *         &lt;element name="KVAsTrafo" type="{http://localhost/elegibilidad}Potencia" minOccurs="0"/>
 *         &lt;element name="PorcentajePerdidasPactadas" type="{http://localhost/elegibilidad}X6" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CondicionesContractualesC", propOrder = {
    "tarifaATR",
    "potenciasContratadas",
    "potenciasMaximas",
    "modoControlPotencia",
    "marcaMedidaBTConPerdidas",
    "kvAsTrafo",
    "porcentajePerdidasPactadas"
})
public class CondicionesContractualesC {

    @XmlElement(name = "TarifaATR", required = true)
    protected String tarifaATR;
    @XmlElement(name = "PotenciasContratadas", required = true)
    protected Potencias potenciasContratadas;
    @XmlElement(name = "PotenciasMaximas")
    protected Potencias potenciasMaximas;
    @XmlElement(name = "ModoControlPotencia")
    protected BigInteger modoControlPotencia;
    @XmlElement(name = "MarcaMedidaBTConPerdidas")
    protected String marcaMedidaBTConPerdidas;
    @XmlElement(name = "KVAsTrafo")
    protected Long kvAsTrafo;
    @XmlElement(name = "PorcentajePerdidasPactadas")
    protected String porcentajePerdidasPactadas;

    /**
     * Gets the value of the tarifaATR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarifaATR() {
        return tarifaATR;
    }

    /**
     * Sets the value of the tarifaATR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarifaATR(String value) {
        this.tarifaATR = value;
    }

    /**
     * Gets the value of the potenciasContratadas property.
     * 
     * @return
     *     possible object is
     *     {@link Potencias }
     *     
     */
    public Potencias getPotenciasContratadas() {
        return potenciasContratadas;
    }

    /**
     * Sets the value of the potenciasContratadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Potencias }
     *     
     */
    public void setPotenciasContratadas(Potencias value) {
        this.potenciasContratadas = value;
    }

    /**
     * Gets the value of the potenciasMaximas property.
     * 
     * @return
     *     possible object is
     *     {@link Potencias }
     *     
     */
    public Potencias getPotenciasMaximas() {
        return potenciasMaximas;
    }

    /**
     * Sets the value of the potenciasMaximas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Potencias }
     *     
     */
    public void setPotenciasMaximas(Potencias value) {
        this.potenciasMaximas = value;
    }

    /**
     * Gets the value of the modoControlPotencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModoControlPotencia() {
        return modoControlPotencia;
    }

    /**
     * Sets the value of the modoControlPotencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModoControlPotencia(BigInteger value) {
        this.modoControlPotencia = value;
    }

    /**
     * Gets the value of the marcaMedidaBTConPerdidas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarcaMedidaBTConPerdidas() {
        return marcaMedidaBTConPerdidas;
    }

    /**
     * Sets the value of the marcaMedidaBTConPerdidas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarcaMedidaBTConPerdidas(String value) {
        this.marcaMedidaBTConPerdidas = value;
    }

    /**
     * Gets the value of the kvAsTrafo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKVAsTrafo() {
        return kvAsTrafo;
    }

    /**
     * Sets the value of the kvAsTrafo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKVAsTrafo(Long value) {
        this.kvAsTrafo = value;
    }

    /**
     * Gets the value of the porcentajePerdidasPactadas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorcentajePerdidasPactadas() {
        return porcentajePerdidasPactadas;
    }

    /**
     * Sets the value of the porcentajePerdidasPactadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorcentajePerdidasPactadas(String value) {
        this.porcentajePerdidasPactadas = value;
    }

}
