//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactoConDireccion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactoConDireccion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NombreDePila" type="{http://localhost/elegibilidad}X45"/>
 *         &lt;element name="PrimerApellido" type="{http://localhost/elegibilidad}X45"/>
 *         &lt;element name="SegundoApellido" type="{http://localhost/elegibilidad}X45" minOccurs="0"/>
 *         &lt;element name="Telefono" type="{http://localhost/elegibilidad}TelefonoInternacional" minOccurs="0"/>
 *         &lt;element name="IndicadorTipoDireccion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="F"/>
 *               &lt;enumeration value="S"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Direccion" type="{http://localhost/elegibilidad}Direccion" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactoConDireccion", propOrder = {
    "nombreDePila",
    "primerApellido",
    "segundoApellido",
    "telefono",
    "indicadorTipoDireccion",
    "direccion"
})
public class ContactoConDireccion {

    @XmlElement(name = "NombreDePila", required = true)
    protected String nombreDePila;
    @XmlElement(name = "PrimerApellido", required = true)
    protected String primerApellido;
    @XmlElement(name = "SegundoApellido")
    protected String segundoApellido;
    @XmlElement(name = "Telefono")
    protected TelefonoInternacional telefono;
    @XmlElement(name = "IndicadorTipoDireccion", required = true)
    protected String indicadorTipoDireccion;
    @XmlElement(name = "Direccion")
    protected Direccion direccion;

    /**
     * Gets the value of the nombreDePila property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreDePila() {
        return nombreDePila;
    }

    /**
     * Sets the value of the nombreDePila property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreDePila(String value) {
        this.nombreDePila = value;
    }

    /**
     * Gets the value of the primerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerApellido() {
        return primerApellido;
    }

    /**
     * Sets the value of the primerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerApellido(String value) {
        this.primerApellido = value;
    }

    /**
     * Gets the value of the segundoApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegundoApellido() {
        return segundoApellido;
    }

    /**
     * Sets the value of the segundoApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegundoApellido(String value) {
        this.segundoApellido = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link TelefonoInternacional }
     *     
     */
    public TelefonoInternacional getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelefonoInternacional }
     *     
     */
    public void setTelefono(TelefonoInternacional value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the indicadorTipoDireccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorTipoDireccion() {
        return indicadorTipoDireccion;
    }

    /**
     * Sets the value of the indicadorTipoDireccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorTipoDireccion(String value) {
        this.indicadorTipoDireccion = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link Direccion }
     *     
     */
    public Direccion getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direccion }
     *     
     */
    public void setDireccion(Direccion value) {
        this.direccion = value;
    }

}
