//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosAparatoICP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosAparatoICP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PeriodoFabricacion" type="{http://localhost/elegibilidad}Decimal4" minOccurs="0"/>
 *         &lt;element name="NumeroSerie" type="{http://localhost/elegibilidad}X10" minOccurs="0"/>
 *         &lt;element name="FuncionAparato" type="{http://localhost/elegibilidad}FuncionAparato" minOccurs="0"/>
 *         &lt;element name="NumIntegradores" type="{http://localhost/elegibilidad}Decimal2" minOccurs="0"/>
 *         &lt;element name="ConstanteEnergia" type="{http://localhost/elegibilidad}DecimalS9V3" minOccurs="0"/>
 *         &lt;element name="ConstanteMaximetro" type="{http://localhost/elegibilidad}DecimalS9V3" minOccurs="0"/>
 *         &lt;element name="RuedasEnteras" type="{http://localhost/elegibilidad}Decimal2" minOccurs="0"/>
 *         &lt;element name="RuedasDecimales" type="{http://localhost/elegibilidad}Decimal2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosAparatoICP", propOrder = {
    "periodoFabricacion",
    "numeroSerie",
    "funcionAparato",
    "numIntegradores",
    "constanteEnergia",
    "constanteMaximetro",
    "ruedasEnteras",
    "ruedasDecimales"
})
public class DatosAparatoICP {

    @XmlElement(name = "PeriodoFabricacion")
    protected BigInteger periodoFabricacion;
    @XmlElement(name = "NumeroSerie")
    protected String numeroSerie;
    @XmlElement(name = "FuncionAparato")
    protected String funcionAparato;
    @XmlElement(name = "NumIntegradores")
    protected BigInteger numIntegradores;
    @XmlElement(name = "ConstanteEnergia")
    protected BigDecimal constanteEnergia;
    @XmlElement(name = "ConstanteMaximetro")
    protected BigDecimal constanteMaximetro;
    @XmlElement(name = "RuedasEnteras")
    protected BigInteger ruedasEnteras;
    @XmlElement(name = "RuedasDecimales")
    protected BigInteger ruedasDecimales;

    /**
     * Gets the value of the periodoFabricacion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriodoFabricacion() {
        return periodoFabricacion;
    }

    /**
     * Sets the value of the periodoFabricacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriodoFabricacion(BigInteger value) {
        this.periodoFabricacion = value;
    }

    /**
     * Gets the value of the numeroSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSerie() {
        return numeroSerie;
    }

    /**
     * Sets the value of the numeroSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSerie(String value) {
        this.numeroSerie = value;
    }

    /**
     * Gets the value of the funcionAparato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuncionAparato() {
        return funcionAparato;
    }

    /**
     * Sets the value of the funcionAparato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuncionAparato(String value) {
        this.funcionAparato = value;
    }

    /**
     * Gets the value of the numIntegradores property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumIntegradores() {
        return numIntegradores;
    }

    /**
     * Sets the value of the numIntegradores property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumIntegradores(BigInteger value) {
        this.numIntegradores = value;
    }

    /**
     * Gets the value of the constanteEnergia property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConstanteEnergia() {
        return constanteEnergia;
    }

    /**
     * Sets the value of the constanteEnergia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConstanteEnergia(BigDecimal value) {
        this.constanteEnergia = value;
    }

    /**
     * Gets the value of the constanteMaximetro property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConstanteMaximetro() {
        return constanteMaximetro;
    }

    /**
     * Sets the value of the constanteMaximetro property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConstanteMaximetro(BigDecimal value) {
        this.constanteMaximetro = value;
    }

    /**
     * Gets the value of the ruedasEnteras property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRuedasEnteras() {
        return ruedasEnteras;
    }

    /**
     * Sets the value of the ruedasEnteras property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRuedasEnteras(BigInteger value) {
        this.ruedasEnteras = value;
    }

    /**
     * Gets the value of the ruedasDecimales property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRuedasDecimales() {
        return ruedasDecimales;
    }

    /**
     * Sets the value of the ruedasDecimales property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRuedasDecimales(BigInteger value) {
        this.ruedasDecimales = value;
    }

}
