//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosAceptacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosAceptacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FechaAceptacion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="PotenciaActual" type="{http://localhost/elegibilidad}Potencia"/>
 *         &lt;element name="ActuacionCampo" type="{http://localhost/elegibilidad}Indicativo"/>
 *         &lt;element name="FechaUltimaLectura" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosAceptacion", propOrder = {
    "fechaAceptacion",
    "potenciaActual",
    "actuacionCampo",
    "fechaUltimaLectura"
})
public class DatosAceptacion {

    @XmlElement(name = "FechaAceptacion", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaAceptacion;
    @XmlElement(name = "PotenciaActual")
    protected long potenciaActual;
    @XmlElement(name = "ActuacionCampo", required = true)
    protected String actuacionCampo;
    @XmlElement(name = "FechaUltimaLectura", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaUltimaLectura;

    /**
     * Gets the value of the fechaAceptacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaAceptacion() {
        return fechaAceptacion;
    }

    /**
     * Sets the value of the fechaAceptacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaAceptacion(XMLGregorianCalendar value) {
        this.fechaAceptacion = value;
    }

    /**
     * Gets the value of the potenciaActual property.
     * 
     */
    public long getPotenciaActual() {
        return potenciaActual;
    }

    /**
     * Sets the value of the potenciaActual property.
     * 
     */
    public void setPotenciaActual(long value) {
        this.potenciaActual = value;
    }

    /**
     * Gets the value of the actuacionCampo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuacionCampo() {
        return actuacionCampo;
    }

    /**
     * Sets the value of the actuacionCampo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuacionCampo(String value) {
        this.actuacionCampo = value;
    }

    /**
     * Gets the value of the fechaUltimaLectura property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaUltimaLectura() {
        return fechaUltimaLectura;
    }

    /**
     * Sets the value of the fechaUltimaLectura property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaUltimaLectura(XMLGregorianCalendar value) {
        this.fechaUltimaLectura = value;
    }

}
