//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosReclamante complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosReclamante">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdReclamante" type="{http://localhost/elegibilidad}IdReclamante"/>
 *         &lt;element name="Nombre" type="{http://localhost/elegibilidad}NombreCliente"/>
 *         &lt;element name="Fax" type="{http://localhost/elegibilidad}TelefonoInternacional" minOccurs="0"/>
 *         &lt;element name="Telefono" type="{http://localhost/elegibilidad}TelefonoInternacional" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosReclamante", propOrder = {
    "idReclamante",
    "nombre",
    "fax",
    "telefono"
})
public class DatosReclamante {

    @XmlElement(name = "IdReclamante", required = true)
    protected IdReclamante idReclamante;
    @XmlElement(name = "Nombre", required = true)
    protected NombreCliente nombre;
    @XmlElement(name = "Fax")
    protected TelefonoInternacional fax;
    @XmlElement(name = "Telefono")
    protected TelefonoInternacional telefono;

    /**
     * Gets the value of the idReclamante property.
     * 
     * @return
     *     possible object is
     *     {@link IdReclamante }
     *     
     */
    public IdReclamante getIdReclamante() {
        return idReclamante;
    }

    /**
     * Sets the value of the idReclamante property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdReclamante }
     *     
     */
    public void setIdReclamante(IdReclamante value) {
        this.idReclamante = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link NombreCliente }
     *     
     */
    public NombreCliente getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link NombreCliente }
     *     
     */
    public void setNombre(NombreCliente value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link TelefonoInternacional }
     *     
     */
    public TelefonoInternacional getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelefonoInternacional }
     *     
     */
    public void setFax(TelefonoInternacional value) {
        this.fax = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link TelefonoInternacional }
     *     
     */
    public TelefonoInternacional getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelefonoInternacional }
     *     
     */
    public void setTelefono(TelefonoInternacional value) {
        this.telefono = value;
    }

}
