//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosReclamacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosReclamacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoMovimientoSolicitud" type="{http://localhost/elegibilidad}IndicativoARO"/>
 *         &lt;element name="TipoReclamacion" type="{http://localhost/elegibilidad}TipoReclamacion" minOccurs="0"/>
 *         &lt;element name="FechaIncidencia" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Comentario" type="{http://localhost/elegibilidad}X400"/>
 *         &lt;element name="IndemnizacionSolicitada" type="{http://localhost/elegibilidad}X13"/>
 *         &lt;element name="FechaLimiteLegal" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosReclamacion", propOrder = {
    "tipoMovimientoSolicitud",
    "tipoReclamacion",
    "fechaIncidencia",
    "comentario",
    "indemnizacionSolicitada",
    "fechaLimiteLegal"
})
public class DatosReclamacion {

    @XmlElement(name = "TipoMovimientoSolicitud", required = true)
    protected String tipoMovimientoSolicitud;
    @XmlElement(name = "TipoReclamacion")
    protected String tipoReclamacion;
    @XmlElement(name = "FechaIncidencia", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaIncidencia;
    @XmlElement(name = "Comentario", required = true)
    protected String comentario;
    @XmlElement(name = "IndemnizacionSolicitada", required = true)
    protected String indemnizacionSolicitada;
    @XmlElement(name = "FechaLimiteLegal")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaLimiteLegal;

    /**
     * Gets the value of the tipoMovimientoSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoMovimientoSolicitud() {
        return tipoMovimientoSolicitud;
    }

    /**
     * Sets the value of the tipoMovimientoSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoMovimientoSolicitud(String value) {
        this.tipoMovimientoSolicitud = value;
    }

    /**
     * Gets the value of the tipoReclamacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoReclamacion() {
        return tipoReclamacion;
    }

    /**
     * Sets the value of the tipoReclamacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoReclamacion(String value) {
        this.tipoReclamacion = value;
    }

    /**
     * Gets the value of the fechaIncidencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaIncidencia() {
        return fechaIncidencia;
    }

    /**
     * Sets the value of the fechaIncidencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaIncidencia(XMLGregorianCalendar value) {
        this.fechaIncidencia = value;
    }

    /**
     * Gets the value of the comentario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * Sets the value of the comentario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComentario(String value) {
        this.comentario = value;
    }

    /**
     * Gets the value of the indemnizacionSolicitada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndemnizacionSolicitada() {
        return indemnizacionSolicitada;
    }

    /**
     * Sets the value of the indemnizacionSolicitada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndemnizacionSolicitada(String value) {
        this.indemnizacionSolicitada = value;
    }

    /**
     * Gets the value of the fechaLimiteLegal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaLimiteLegal() {
        return fechaLimiteLegal;
    }

    /**
     * Sets the value of the fechaLimiteLegal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaLimiteLegal(XMLGregorianCalendar value) {
        this.fechaLimiteLegal = value;
    }

}
