//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosTitular complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosTitular">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoTitular" type="{http://localhost/elegibilidad}X2" minOccurs="0"/>
 *         &lt;element name="Titular" type="{http://localhost/elegibilidad}X50" minOccurs="0"/>
 *         &lt;element name="Calle" type="{http://localhost/elegibilidad}X80" minOccurs="0"/>
 *         &lt;element name="Poblacion" type="{http://localhost/elegibilidad}X45" minOccurs="0"/>
 *         &lt;element name="CodPostal" type="{http://localhost/elegibilidad}Decimal5" minOccurs="0"/>
 *         &lt;element name="Provincia" type="{http://localhost/elegibilidad}X45" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosTitular", propOrder = {
    "tipoTitular",
    "titular",
    "calle",
    "poblacion",
    "codPostal",
    "provincia"
})
public class DatosTitular {

    @XmlElement(name = "TipoTitular")
    protected String tipoTitular;
    @XmlElement(name = "Titular")
    protected String titular;
    @XmlElement(name = "Calle")
    protected String calle;
    @XmlElement(name = "Poblacion")
    protected String poblacion;
    @XmlElement(name = "CodPostal")
    protected BigInteger codPostal;
    @XmlElement(name = "Provincia")
    protected String provincia;

    /**
     * Gets the value of the tipoTitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTitular() {
        return tipoTitular;
    }

    /**
     * Sets the value of the tipoTitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTitular(String value) {
        this.tipoTitular = value;
    }

    /**
     * Gets the value of the titular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitular() {
        return titular;
    }

    /**
     * Sets the value of the titular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitular(String value) {
        this.titular = value;
    }

    /**
     * Gets the value of the calle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalle() {
        return calle;
    }

    /**
     * Sets the value of the calle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalle(String value) {
        this.calle = value;
    }

    /**
     * Gets the value of the poblacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoblacion() {
        return poblacion;
    }

    /**
     * Sets the value of the poblacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoblacion(String value) {
        this.poblacion = value;
    }

    /**
     * Gets the value of the codPostal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodPostal() {
        return codPostal;
    }

    /**
     * Sets the value of the codPostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodPostal(BigInteger value) {
        this.codPostal = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvincia(String value) {
        this.provincia = value;
    }

}
