//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosAutolecturas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosAutolecturas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoDH" type="{http://localhost/elegibilidad}TipoDH"/>
 *         &lt;element name="Periodo" type="{http://localhost/elegibilidad}TipoCodigoPeriodoDH"/>
 *         &lt;element name="MagnitudMedida" type="{http://localhost/elegibilidad}MagnitudMedida"/>
 *         &lt;element name="Aparato" type="{http://localhost/elegibilidad}ModeloAparatoAutolecturas"/>
 *         &lt;element name="Procedencia" type="{http://localhost/elegibilidad}Procedencia"/>
 *         &lt;element name="LecturaPropuesta" type="{http://localhost/elegibilidad}DecimalS10V2"/>
 *         &lt;element name="FechaLectura" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosAutolecturas", propOrder = {
    "tipoDH",
    "periodo",
    "magnitudMedida",
    "aparato",
    "procedencia",
    "lecturaPropuesta",
    "fechaLectura"
})
public class DatosAutolecturas {

    @XmlElement(name = "TipoDH", required = true)
    protected String tipoDH;
    @XmlElement(name = "Periodo", required = true)
    protected String periodo;
    @XmlElement(name = "MagnitudMedida", required = true)
    protected MagnitudMedida magnitudMedida;
    @XmlElement(name = "Aparato", required = true)
    protected ModeloAparatoAutolecturas aparato;
    @XmlElement(name = "Procedencia", required = true)
    protected String procedencia;
    @XmlElement(name = "LecturaPropuesta", required = true)
    protected BigDecimal lecturaPropuesta;
    @XmlElement(name = "FechaLectura", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaLectura;

    /**
     * Gets the value of the tipoDH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDH() {
        return tipoDH;
    }

    /**
     * Sets the value of the tipoDH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDH(String value) {
        this.tipoDH = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodo(String value) {
        this.periodo = value;
    }

    /**
     * Gets the value of the magnitudMedida property.
     * 
     * @return
     *     possible object is
     *     {@link MagnitudMedida }
     *     
     */
    public MagnitudMedida getMagnitudMedida() {
        return magnitudMedida;
    }

    /**
     * Sets the value of the magnitudMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagnitudMedida }
     *     
     */
    public void setMagnitudMedida(MagnitudMedida value) {
        this.magnitudMedida = value;
    }

    /**
     * Gets the value of the aparato property.
     * 
     * @return
     *     possible object is
     *     {@link ModeloAparatoAutolecturas }
     *     
     */
    public ModeloAparatoAutolecturas getAparato() {
        return aparato;
    }

    /**
     * Sets the value of the aparato property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModeloAparatoAutolecturas }
     *     
     */
    public void setAparato(ModeloAparatoAutolecturas value) {
        this.aparato = value;
    }

    /**
     * Gets the value of the procedencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedencia() {
        return procedencia;
    }

    /**
     * Sets the value of the procedencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedencia(String value) {
        this.procedencia = value;
    }

    /**
     * Gets the value of the lecturaPropuesta property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLecturaPropuesta() {
        return lecturaPropuesta;
    }

    /**
     * Sets the value of the lecturaPropuesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLecturaPropuesta(BigDecimal value) {
        this.lecturaPropuesta = value;
    }

    /**
     * Gets the value of the fechaLectura property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaLectura() {
        return fechaLectura;
    }

    /**
     * Sets the value of the fechaLectura property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaLectura(XMLGregorianCalendar value) {
        this.fechaLectura = value;
    }

}
