//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosReclamacionFactura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosReclamacionFactura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodFiscalFactura" type="{http://localhost/elegibilidad}X30"/>
 *         &lt;element name="ImporteFactReclamada" type="{http://localhost/elegibilidad}X15"/>
 *         &lt;element name="CodAgrupacion" type="{http://localhost/elegibilidad}X20" minOccurs="0"/>
 *         &lt;element name="FechaFactura" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FechaDesdeFact" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FechaHastaFact" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosReclamacionFactura", propOrder = {
    "codFiscalFactura",
    "importeFactReclamada",
    "codAgrupacion",
    "fechaFactura",
    "fechaDesdeFact",
    "fechaHastaFact"
})
public class DatosReclamacionFactura {

    @XmlElement(name = "CodFiscalFactura", required = true)
    protected String codFiscalFactura;
    @XmlElement(name = "ImporteFactReclamada", required = true)
    protected String importeFactReclamada;
    @XmlElement(name = "CodAgrupacion")
    protected String codAgrupacion;
    @XmlElement(name = "FechaFactura", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaFactura;
    @XmlElement(name = "FechaDesdeFact")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaDesdeFact;
    @XmlElement(name = "FechaHastaFact")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaHastaFact;

    /**
     * Gets the value of the codFiscalFactura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodFiscalFactura() {
        return codFiscalFactura;
    }

    /**
     * Sets the value of the codFiscalFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodFiscalFactura(String value) {
        this.codFiscalFactura = value;
    }

    /**
     * Gets the value of the importeFactReclamada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteFactReclamada() {
        return importeFactReclamada;
    }

    /**
     * Sets the value of the importeFactReclamada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteFactReclamada(String value) {
        this.importeFactReclamada = value;
    }

    /**
     * Gets the value of the codAgrupacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodAgrupacion() {
        return codAgrupacion;
    }

    /**
     * Sets the value of the codAgrupacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodAgrupacion(String value) {
        this.codAgrupacion = value;
    }

    /**
     * Gets the value of the fechaFactura property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaFactura() {
        return fechaFactura;
    }

    /**
     * Sets the value of the fechaFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaFactura(XMLGregorianCalendar value) {
        this.fechaFactura = value;
    }

    /**
     * Gets the value of the fechaDesdeFact property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaDesdeFact() {
        return fechaDesdeFact;
    }

    /**
     * Sets the value of the fechaDesdeFact property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaDesdeFact(XMLGregorianCalendar value) {
        this.fechaDesdeFact = value;
    }

    /**
     * Gets the value of the fechaHastaFact property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaHastaFact() {
        return fechaHastaFact;
    }

    /**
     * Sets the value of the fechaHastaFact property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaHastaFact(XMLGregorianCalendar value) {
        this.fechaHastaFact = value;
    }

}
