//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosAPM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosAPM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoApm" type="{http://localhost/elegibilidad}X35"/>
 *         &lt;element name="PotenciaInstAT" type="{http://localhost/elegibilidad}Decimal11"/>
 *         &lt;element name="FechaEmisionApm" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FechaCaducidadApm" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TensionSuministroAPM" type="{http://localhost/elegibilidad}TensionSuministroCIEyAPM"/>
 *         &lt;choice>
 *           &lt;element name="NifInstalador" type="{http://localhost/elegibilidad}X9"/>
 *           &lt;element name="CodigoInstalador" type="{http://localhost/elegibilidad}X9"/>
 *         &lt;/choice>
 *         &lt;element name="NombreInstalador" type="{http://localhost/elegibilidad}X45"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosAPM", propOrder = {
    "codigoApm",
    "potenciaInstAT",
    "fechaEmisionApm",
    "fechaCaducidadApm",
    "tensionSuministroAPM",
    "nifInstalador",
    "codigoInstalador",
    "nombreInstalador"
})
public class DatosAPM {

    @XmlElement(name = "CodigoApm", required = true)
    protected String codigoApm;
    @XmlElement(name = "PotenciaInstAT")
    protected long potenciaInstAT;
    @XmlElement(name = "FechaEmisionApm", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaEmisionApm;
    @XmlElement(name = "FechaCaducidadApm")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaCaducidadApm;
    @XmlElement(name = "TensionSuministroAPM", required = true)
    protected String tensionSuministroAPM;
    @XmlElement(name = "NifInstalador")
    protected String nifInstalador;
    @XmlElement(name = "CodigoInstalador")
    protected String codigoInstalador;
    @XmlElement(name = "NombreInstalador", required = true)
    protected String nombreInstalador;

    /**
     * Gets the value of the codigoApm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoApm() {
        return codigoApm;
    }

    /**
     * Sets the value of the codigoApm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoApm(String value) {
        this.codigoApm = value;
    }

    /**
     * Gets the value of the potenciaInstAT property.
     * 
     */
    public long getPotenciaInstAT() {
        return potenciaInstAT;
    }

    /**
     * Sets the value of the potenciaInstAT property.
     * 
     */
    public void setPotenciaInstAT(long value) {
        this.potenciaInstAT = value;
    }

    /**
     * Gets the value of the fechaEmisionApm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEmisionApm() {
        return fechaEmisionApm;
    }

    /**
     * Sets the value of the fechaEmisionApm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEmisionApm(XMLGregorianCalendar value) {
        this.fechaEmisionApm = value;
    }

    /**
     * Gets the value of the fechaCaducidadApm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaCaducidadApm() {
        return fechaCaducidadApm;
    }

    /**
     * Sets the value of the fechaCaducidadApm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaCaducidadApm(XMLGregorianCalendar value) {
        this.fechaCaducidadApm = value;
    }

    /**
     * Gets the value of the tensionSuministroAPM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTensionSuministroAPM() {
        return tensionSuministroAPM;
    }

    /**
     * Sets the value of the tensionSuministroAPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTensionSuministroAPM(String value) {
        this.tensionSuministroAPM = value;
    }

    /**
     * Gets the value of the nifInstalador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNifInstalador() {
        return nifInstalador;
    }

    /**
     * Sets the value of the nifInstalador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNifInstalador(String value) {
        this.nifInstalador = value;
    }

    /**
     * Gets the value of the codigoInstalador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoInstalador() {
        return codigoInstalador;
    }

    /**
     * Sets the value of the codigoInstalador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoInstalador(String value) {
        this.codigoInstalador = value;
    }

    /**
     * Gets the value of the nombreInstalador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreInstalador() {
        return nombreInstalador;
    }

    /**
     * Sets the value of the nombreInstalador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreInstalador(String value) {
        this.nombreInstalador = value;
    }

}
