//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DireccionSinCodPostal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DireccionSinCodPostal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pais" type="{http://localhost/elegibilidad}X25"/>
 *         &lt;element name="Provincia" type="{http://localhost/elegibilidad}Decimal2"/>
 *         &lt;element name="Municipio" type="{http://localhost/elegibilidad}Decimal7"/>
 *         &lt;element name="Poblacion" type="{http://localhost/elegibilidad}Decimal7"/>
 *         &lt;element name="TipoVia" type="{http://localhost/elegibilidad}TipoVia"/>
 *         &lt;element name="Calle" type="{http://localhost/elegibilidad}X30"/>
 *         &lt;element name="NumeroFinca" type="{http://localhost/elegibilidad}X5"/>
 *         &lt;element name="DuplicadorFinca" type="{http://localhost/elegibilidad}X3" minOccurs="0"/>
 *         &lt;element name="Escalera" type="{http://localhost/elegibilidad}Escalera" minOccurs="0"/>
 *         &lt;element name="Piso" type="{http://localhost/elegibilidad}Piso" minOccurs="0"/>
 *         &lt;element name="Puerta" type="{http://localhost/elegibilidad}Puerta" minOccurs="0"/>
 *         &lt;element name="TipoAclaradorFinca" type="{http://localhost/elegibilidad}TipoAclaradorFinca" minOccurs="0"/>
 *         &lt;element name="AclaradorFinca" type="{http://localhost/elegibilidad}X40" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DireccionSinCodPostal", propOrder = {
    "pais",
    "provincia",
    "municipio",
    "poblacion",
    "tipoVia",
    "calle",
    "numeroFinca",
    "duplicadorFinca",
    "escalera",
    "piso",
    "puerta",
    "tipoAclaradorFinca",
    "aclaradorFinca"
})
public class DireccionSinCodPostal {

    @XmlElement(name = "Pais", required = true)
    protected String pais;
    @XmlElement(name = "Provincia", required = true)
    protected BigInteger provincia;
    @XmlElement(name = "Municipio")
    protected long municipio;
    @XmlElement(name = "Poblacion")
    protected long poblacion;
    @XmlElement(name = "TipoVia", required = true)
    protected TipoVia tipoVia;
    @XmlElement(name = "Calle", required = true)
    protected String calle;
    @XmlElement(name = "NumeroFinca", required = true)
    protected String numeroFinca;
    @XmlElement(name = "DuplicadorFinca")
    protected String duplicadorFinca;
    @XmlElement(name = "Escalera")
    protected String escalera;
    @XmlElement(name = "Piso")
    protected String piso;
    @XmlElement(name = "Puerta")
    protected String puerta;
    @XmlElement(name = "TipoAclaradorFinca")
    protected String tipoAclaradorFinca;
    @XmlElement(name = "AclaradorFinca")
    protected String aclaradorFinca;

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProvincia(BigInteger value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     */
    public long getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     */
    public void setMunicipio(long value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the poblacion property.
     * 
     */
    public long getPoblacion() {
        return poblacion;
    }

    /**
     * Sets the value of the poblacion property.
     * 
     */
    public void setPoblacion(long value) {
        this.poblacion = value;
    }

    /**
     * Gets the value of the tipoVia property.
     * 
     * @return
     *     possible object is
     *     {@link TipoVia }
     *     
     */
    public TipoVia getTipoVia() {
        return tipoVia;
    }

    /**
     * Sets the value of the tipoVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoVia }
     *     
     */
    public void setTipoVia(TipoVia value) {
        this.tipoVia = value;
    }

    /**
     * Gets the value of the calle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalle() {
        return calle;
    }

    /**
     * Sets the value of the calle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalle(String value) {
        this.calle = value;
    }

    /**
     * Gets the value of the numeroFinca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFinca() {
        return numeroFinca;
    }

    /**
     * Sets the value of the numeroFinca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFinca(String value) {
        this.numeroFinca = value;
    }

    /**
     * Gets the value of the duplicadorFinca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuplicadorFinca() {
        return duplicadorFinca;
    }

    /**
     * Sets the value of the duplicadorFinca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuplicadorFinca(String value) {
        this.duplicadorFinca = value;
    }

    /**
     * Gets the value of the escalera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEscalera() {
        return escalera;
    }

    /**
     * Sets the value of the escalera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEscalera(String value) {
        this.escalera = value;
    }

    /**
     * Gets the value of the piso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiso() {
        return piso;
    }

    /**
     * Sets the value of the piso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiso(String value) {
        this.piso = value;
    }

    /**
     * Gets the value of the puerta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuerta() {
        return puerta;
    }

    /**
     * Sets the value of the puerta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuerta(String value) {
        this.puerta = value;
    }

    /**
     * Gets the value of the tipoAclaradorFinca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAclaradorFinca() {
        return tipoAclaradorFinca;
    }

    /**
     * Sets the value of the tipoAclaradorFinca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAclaradorFinca(String value) {
        this.tipoAclaradorFinca = value;
    }

    /**
     * Gets the value of the aclaradorFinca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAclaradorFinca() {
        return aclaradorFinca;
    }

    /**
     * Sets the value of the aclaradorFinca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAclaradorFinca(String value) {
        this.aclaradorFinca = value;
    }

}
