//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocTecnica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocTecnica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosCie" type="{http://localhost/elegibilidad}DatosCIE" minOccurs="0"/>
 *         &lt;element name="DatosApm" type="{http://localhost/elegibilidad}DatosAPM" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocTecnica", propOrder = {
    "datosCie",
    "datosApm"
})
public class DocTecnica {

    @XmlElement(name = "DatosCie")
    protected DatosCIE datosCie;
    @XmlElement(name = "DatosApm")
    protected DatosAPM datosApm;

    /**
     * Gets the value of the datosCie property.
     * 
     * @return
     *     possible object is
     *     {@link DatosCIE }
     *     
     */
    public DatosCIE getDatosCie() {
        return datosCie;
    }

    /**
     * Sets the value of the datosCie property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosCIE }
     *     
     */
    public void setDatosCie(DatosCIE value) {
        this.datosCie = value;
    }

    /**
     * Gets the value of the datosApm property.
     * 
     * @return
     *     possible object is
     *     {@link DatosAPM }
     *     
     */
    public DatosAPM getDatosApm() {
        return datosApm;
    }

    /**
     * Sets the value of the datosApm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosAPM }
     *     
     */
    public void setDatosApm(DatosAPM value) {
        this.datosApm = value;
    }

}
