//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Importes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Importes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImportesTerminoPotencia" type="{http://localhost/elegibilidad}ImportesTerminoPotencia" minOccurs="0"/>
 *         &lt;element name="ImportesTerminoEnergia" type="{http://localhost/elegibilidad}ImportesTerminoEnergia" minOccurs="0"/>
 *         &lt;element name="ImporteReactiva" type="{http://localhost/elegibilidad}Importe" minOccurs="0"/>
 *         &lt;element name="ImporteExcesoPotencia" type="{http://localhost/elegibilidad}Importe" minOccurs="0"/>
 *         &lt;element name="ImporteAlquileres" type="{http://localhost/elegibilidad}Importe" minOccurs="0"/>
 *         &lt;element name="ImportesOtrosConceptos" type="{http://localhost/elegibilidad}ImportesOtrosConceptos" minOccurs="0"/>
 *         &lt;element name="ImpuestoElectrico" type="{http://localhost/elegibilidad}Importe" minOccurs="0"/>
 *         &lt;element name="IVA" type="{http://localhost/elegibilidad}Importe" minOccurs="0"/>
 *         &lt;element name="ImporteTotal" type="{http://localhost/elegibilidad}Importe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Importes", propOrder = {
    "importesTerminoPotencia",
    "importesTerminoEnergia",
    "importeReactiva",
    "importeExcesoPotencia",
    "importeAlquileres",
    "importesOtrosConceptos",
    "impuestoElectrico",
    "iva",
    "importeTotal"
})
public class Importes {

    @XmlElement(name = "ImportesTerminoPotencia")
    protected ImportesTerminoPotencia importesTerminoPotencia;
    @XmlElement(name = "ImportesTerminoEnergia")
    protected ImportesTerminoEnergia importesTerminoEnergia;
    @XmlElement(name = "ImporteReactiva")
    protected Long importeReactiva;
    @XmlElement(name = "ImporteExcesoPotencia")
    protected Long importeExcesoPotencia;
    @XmlElement(name = "ImporteAlquileres")
    protected Long importeAlquileres;
    @XmlElement(name = "ImportesOtrosConceptos")
    protected ImportesOtrosConceptos importesOtrosConceptos;
    @XmlElement(name = "ImpuestoElectrico")
    protected Long impuestoElectrico;
    @XmlElement(name = "IVA")
    protected Long iva;
    @XmlElement(name = "ImporteTotal")
    protected Long importeTotal;

    /**
     * Gets the value of the importesTerminoPotencia property.
     * 
     * @return
     *     possible object is
     *     {@link ImportesTerminoPotencia }
     *     
     */
    public ImportesTerminoPotencia getImportesTerminoPotencia() {
        return importesTerminoPotencia;
    }

    /**
     * Sets the value of the importesTerminoPotencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportesTerminoPotencia }
     *     
     */
    public void setImportesTerminoPotencia(ImportesTerminoPotencia value) {
        this.importesTerminoPotencia = value;
    }

    /**
     * Gets the value of the importesTerminoEnergia property.
     * 
     * @return
     *     possible object is
     *     {@link ImportesTerminoEnergia }
     *     
     */
    public ImportesTerminoEnergia getImportesTerminoEnergia() {
        return importesTerminoEnergia;
    }

    /**
     * Sets the value of the importesTerminoEnergia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportesTerminoEnergia }
     *     
     */
    public void setImportesTerminoEnergia(ImportesTerminoEnergia value) {
        this.importesTerminoEnergia = value;
    }

    /**
     * Gets the value of the importeReactiva property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getImporteReactiva() {
        return importeReactiva;
    }

    /**
     * Sets the value of the importeReactiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImporteReactiva(Long value) {
        this.importeReactiva = value;
    }

    /**
     * Gets the value of the importeExcesoPotencia property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getImporteExcesoPotencia() {
        return importeExcesoPotencia;
    }

    /**
     * Sets the value of the importeExcesoPotencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImporteExcesoPotencia(Long value) {
        this.importeExcesoPotencia = value;
    }

    /**
     * Gets the value of the importeAlquileres property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getImporteAlquileres() {
        return importeAlquileres;
    }

    /**
     * Sets the value of the importeAlquileres property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImporteAlquileres(Long value) {
        this.importeAlquileres = value;
    }

    /**
     * Gets the value of the importesOtrosConceptos property.
     * 
     * @return
     *     possible object is
     *     {@link ImportesOtrosConceptos }
     *     
     */
    public ImportesOtrosConceptos getImportesOtrosConceptos() {
        return importesOtrosConceptos;
    }

    /**
     * Sets the value of the importesOtrosConceptos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportesOtrosConceptos }
     *     
     */
    public void setImportesOtrosConceptos(ImportesOtrosConceptos value) {
        this.importesOtrosConceptos = value;
    }

    /**
     * Gets the value of the impuestoElectrico property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getImpuestoElectrico() {
        return impuestoElectrico;
    }

    /**
     * Sets the value of the impuestoElectrico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImpuestoElectrico(Long value) {
        this.impuestoElectrico = value;
    }

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIVA() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIVA(Long value) {
        this.iva = value;
    }

    /**
     * Gets the value of the importeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getImporteTotal() {
        return importeTotal;
    }

    /**
     * Sets the value of the importeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImporteTotal(Long value) {
        this.importeTotal = value;
    }

}
