//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MagnitudMedida.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MagnitudMedida">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AE"/>
 *     &lt;enumeration value="AS"/>
 *     &lt;enumeration value="R1"/>
 *     &lt;enumeration value="R2"/>
 *     &lt;enumeration value="R3"/>
 *     &lt;enumeration value="R4"/>
 *     &lt;enumeration value="PM"/>
 *     &lt;enumeration value="EP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MagnitudMedida")
@XmlEnum
public enum MagnitudMedida {

    AE("AE"),
    AS("AS"),
    @XmlEnumValue("R1")
    R_1("R1"),
    @XmlEnumValue("R2")
    R_2("R2"),
    @XmlEnumValue("R3")
    R_3("R3"),
    @XmlEnumValue("R4")
    R_4("R4"),
    PM("PM"),
    EP("EP");
    private final String value;

    MagnitudMedida(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MagnitudMedida fromValue(String v) {
        for (MagnitudMedida c: MagnitudMedida.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
