//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedidaAparato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedidaAparato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoDH" type="{http://localhost/elegibilidad}TipoDH"/>
 *         &lt;element name="Periodo" type="{http://localhost/elegibilidad}TipoCodigoPeriodoDH"/>
 *         &lt;element name="MagnitudMedida" type="{http://localhost/elegibilidad}MagnitudMedida"/>
 *         &lt;element name="Procedencia" type="{http://localhost/elegibilidad}Procedencia"/>
 *         &lt;element name="LecturaAnterior" type="{http://localhost/elegibilidad}DecimalS10V2"/>
 *         &lt;element name="Anomalia" type="{http://localhost/elegibilidad}AnomaliaMedida" minOccurs="0"/>
 *         &lt;element name="TextoAnomalia" type="{http://localhost/elegibilidad}X250" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedidaAparato", propOrder = {
    "tipoDH",
    "periodo",
    "magnitudMedida",
    "procedencia",
    "lecturaAnterior",
    "anomalia",
    "textoAnomalia"
})
public class MedidaAparato {

    @XmlElement(name = "TipoDH", required = true)
    protected String tipoDH;
    @XmlElement(name = "Periodo", required = true)
    protected String periodo;
    @XmlElement(name = "MagnitudMedida", required = true)
    protected MagnitudMedida magnitudMedida;
    @XmlElement(name = "Procedencia", required = true)
    protected String procedencia;
    @XmlElement(name = "LecturaAnterior", required = true)
    protected BigDecimal lecturaAnterior;
    @XmlElement(name = "Anomalia")
    protected String anomalia;
    @XmlElement(name = "TextoAnomalia")
    protected String textoAnomalia;

    /**
     * Gets the value of the tipoDH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDH() {
        return tipoDH;
    }

    /**
     * Sets the value of the tipoDH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDH(String value) {
        this.tipoDH = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodo(String value) {
        this.periodo = value;
    }

    /**
     * Gets the value of the magnitudMedida property.
     * 
     * @return
     *     possible object is
     *     {@link MagnitudMedida }
     *     
     */
    public MagnitudMedida getMagnitudMedida() {
        return magnitudMedida;
    }

    /**
     * Sets the value of the magnitudMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagnitudMedida }
     *     
     */
    public void setMagnitudMedida(MagnitudMedida value) {
        this.magnitudMedida = value;
    }

    /**
     * Gets the value of the procedencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedencia() {
        return procedencia;
    }

    /**
     * Sets the value of the procedencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedencia(String value) {
        this.procedencia = value;
    }

    /**
     * Gets the value of the lecturaAnterior property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLecturaAnterior() {
        return lecturaAnterior;
    }

    /**
     * Sets the value of the lecturaAnterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLecturaAnterior(BigDecimal value) {
        this.lecturaAnterior = value;
    }

    /**
     * Gets the value of the anomalia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnomalia() {
        return anomalia;
    }

    /**
     * Sets the value of the anomalia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnomalia(String value) {
        this.anomalia = value;
    }

    /**
     * Gets the value of the textoAnomalia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoAnomalia() {
        return textoAnomalia;
    }

    /**
     * Sets the value of the textoAnomalia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoAnomalia(String value) {
        this.textoAnomalia = value;
    }

}
