//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecera" type="{http://localhost/elegibilidad}Cabecera"/>
 *         &lt;element name="Facturas" type="{http://localhost/elegibilidad}Facturas"/>
 *         &lt;element name="OtrosDatosFactura" type="{http://localhost/elegibilidad}OtrosDatosFactura" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AgenteSolicitante" use="required" type="{http://localhost/elegibilidad}Agente" />
 *       &lt;attribute name="Firmar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cabecera",
    "facturas",
    "otrosDatosFactura",
    "any"
})
@XmlRootElement(name = "MensajeFacturacion")
public class MensajeFacturacion {

    @XmlElement(name = "Cabecera", required = true)
    protected Cabecera cabecera;
    @XmlElement(name = "Facturas", required = true)
    protected Facturas facturas;
    @XmlElement(name = "OtrosDatosFactura")
    protected OtrosDatosFactura otrosDatosFactura;
    @XmlAnyElement
    protected Element any;
    @XmlAttribute(name = "AgenteSolicitante", required = true)
    protected String agenteSolicitante;
    @XmlAttribute(name = "Firmar")
    protected String firmar;

    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link Cabecera }
     *     
     */
    public Cabecera getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cabecera }
     *     
     */
    public void setCabecera(Cabecera value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the facturas property.
     * 
     * @return
     *     possible object is
     *     {@link Facturas }
     *     
     */
    public Facturas getFacturas() {
        return facturas;
    }

    /**
     * Sets the value of the facturas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facturas }
     *     
     */
    public void setFacturas(Facturas value) {
        this.facturas = value;
    }

    /**
     * Gets the value of the otrosDatosFactura property.
     * 
     * @return
     *     possible object is
     *     {@link OtrosDatosFactura }
     *     
     */
    public OtrosDatosFactura getOtrosDatosFactura() {
        return otrosDatosFactura;
    }

    /**
     * Sets the value of the otrosDatosFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtrosDatosFactura }
     *     
     */
    public void setOtrosDatosFactura(OtrosDatosFactura value) {
        this.otrosDatosFactura = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setAny(Element value) {
        this.any = value;
    }

    /**
     * Gets the value of the agenteSolicitante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgenteSolicitante() {
        return agenteSolicitante;
    }

    /**
     * Sets the value of the agenteSolicitante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgenteSolicitante(String value) {
        this.agenteSolicitante = value;
    }

    /**
     * Gets the value of the firmar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirmar() {
        return firmar;
    }

    /**
     * Sets the value of the firmar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirmar(String value) {
        this.firmar = value;
    }

}
