//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModeloAparatoAutolecturas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModeloAparatoAutolecturas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tipo" type="{http://localhost/elegibilidad}TipoAparato"/>
 *         &lt;element name="Marca" type="{http://localhost/elegibilidad}MarcaAparato"/>
 *         &lt;element name="ModeloMarca" type="{http://localhost/elegibilidad}X30" minOccurs="0"/>
 *         &lt;element name="NumeroSerie" type="{http://localhost/elegibilidad}X10"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModeloAparatoAutolecturas", propOrder = {
    "tipo",
    "marca",
    "modeloMarca",
    "numeroSerie"
})
public class ModeloAparatoAutolecturas {

    @XmlElement(name = "Tipo", required = true)
    protected TipoAparato tipo;
    @XmlElement(name = "Marca", required = true)
    protected String marca;
    @XmlElement(name = "ModeloMarca")
    protected String modeloMarca;
    @XmlElement(name = "NumeroSerie", required = true)
    protected String numeroSerie;

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoAparato }
     *     
     */
    public TipoAparato getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoAparato }
     *     
     */
    public void setTipo(TipoAparato value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the marca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarca() {
        return marca;
    }

    /**
     * Sets the value of the marca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarca(String value) {
        this.marca = value;
    }

    /**
     * Gets the value of the modeloMarca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeloMarca() {
        return modeloMarca;
    }

    /**
     * Sets the value of the modeloMarca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeloMarca(String value) {
        this.modeloMarca = value;
    }

    /**
     * Gets the value of the numeroSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSerie() {
        return numeroSerie;
    }

    /**
     * Sets the value of the numeroSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSerie(String value) {
        this.numeroSerie = value;
    }

}
