//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the electricidad package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: electricidad
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnergiasAFacturar }
     * 
     */
    public EnergiasAFacturar createEnergiasAFacturar() {
        return new EnergiasAFacturar();
    }

    /**
     * Create an instance of {@link ReactivasAFacturar }
     * 
     */
    public ReactivasAFacturar createReactivasAFacturar() {
        return new ReactivasAFacturar();
    }

    /**
     * Create an instance of {@link ExcesosPotAFacturar }
     * 
     */
    public ExcesosPotAFacturar createExcesosPotAFacturar() {
        return new ExcesosPotAFacturar();
    }

    /**
     * Create an instance of {@link OtrosConceptos }
     * 
     */
    public OtrosConceptos createOtrosConceptos() {
        return new OtrosConceptos();
    }

    /**
     * Create an instance of {@link PotenciasAFacturar }
     * 
     */
    public PotenciasAFacturar createPotenciasAFacturar() {
        return new PotenciasAFacturar();
    }

    /**
     * Create an instance of {@link ImportesTerminoEnergia }
     * 
     */
    public ImportesTerminoEnergia createImportesTerminoEnergia() {
        return new ImportesTerminoEnergia();
    }

    /**
     * Create an instance of {@link Potencias }
     * 
     */
    public Potencias createPotencias() {
        return new Potencias();
    }

    /**
     * Create an instance of {@link ImportesOtrosConceptos }
     * 
     */
    public ImportesOtrosConceptos createImportesOtrosConceptos() {
        return new ImportesOtrosConceptos();
    }

    /**
     * Create an instance of {@link ImportesTerminoPotencia }
     * 
     */
    public ImportesTerminoPotencia createImportesTerminoPotencia() {
        return new ImportesTerminoPotencia();
    }

    /**
     * Create an instance of {@link Facturas }
     * 
     */
    public Facturas createFacturas() {
        return new Facturas();
    }

    /**
     * Create an instance of {@link Facturas.OtrasFacturas }
     * 
     */
    public Facturas.OtrasFacturas createFacturasOtrasFacturas() {
        return new Facturas.OtrasFacturas();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR }
     * 
     */
    public Facturas.FacturaATR createFacturasFacturaATR() {
        return new Facturas.FacturaATR();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Medidas }
     * 
     */
    public Facturas.FacturaATR.Medidas createFacturasFacturaATRMedidas() {
        return new Facturas.FacturaATR.Medidas();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Medidas.Aparato }
     * 
     */
    public Facturas.FacturaATR.Medidas.Aparato createFacturasFacturaATRMedidasAparato() {
        return new Facturas.FacturaATR.Medidas.Aparato();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Medidas.Aparato.Integrador }
     * 
     */
    public Facturas.FacturaATR.Medidas.Aparato.Integrador createFacturasFacturaATRMedidasAparatoIntegrador() {
        return new Facturas.FacturaATR.Medidas.Aparato.Integrador();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Refacturaciones }
     * 
     */
    public Facturas.FacturaATR.Refacturaciones createFacturasFacturaATRRefacturaciones() {
        return new Facturas.FacturaATR.Refacturaciones();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.EnergiaReactiva }
     * 
     */
    public Facturas.FacturaATR.EnergiaReactiva createFacturasFacturaATREnergiaReactiva() {
        return new Facturas.FacturaATR.EnergiaReactiva();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.EnergiaReactiva.TerminoEnergiaReactiva }
     * 
     */
    public Facturas.FacturaATR.EnergiaReactiva.TerminoEnergiaReactiva createFacturasFacturaATREnergiaReactivaTerminoEnergiaReactiva() {
        return new Facturas.FacturaATR.EnergiaReactiva.TerminoEnergiaReactiva();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.EnergiaActiva }
     * 
     */
    public Facturas.FacturaATR.EnergiaActiva createFacturasFacturaATREnergiaActiva() {
        return new Facturas.FacturaATR.EnergiaActiva();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.EnergiaActiva.TerminoEnergiaActiva }
     * 
     */
    public Facturas.FacturaATR.EnergiaActiva.TerminoEnergiaActiva createFacturasFacturaATREnergiaActivaTerminoEnergiaActiva() {
        return new Facturas.FacturaATR.EnergiaActiva.TerminoEnergiaActiva();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.ExcesoPotencia }
     * 
     */
    public Facturas.FacturaATR.ExcesoPotencia createFacturasFacturaATRExcesoPotencia() {
        return new Facturas.FacturaATR.ExcesoPotencia();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Potencia }
     * 
     */
    public Facturas.FacturaATR.Potencia createFacturasFacturaATRPotencia() {
        return new Facturas.FacturaATR.Potencia();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Potencia.TerminoPotencia }
     * 
     */
    public Facturas.FacturaATR.Potencia.TerminoPotencia createFacturasFacturaATRPotenciaTerminoPotencia() {
        return new Facturas.FacturaATR.Potencia.TerminoPotencia();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.DatosGeneralesFacturaATR }
     * 
     */
    public Facturas.FacturaATR.DatosGeneralesFacturaATR createFacturasFacturaATRDatosGeneralesFacturaATR() {
        return new Facturas.FacturaATR.DatosGeneralesFacturaATR();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.DatosGeneralesFacturaATR.DatosFacturaATR }
     * 
     */
    public Facturas.FacturaATR.DatosGeneralesFacturaATR.DatosFacturaATR createFacturasFacturaATRDatosGeneralesFacturaATRDatosFacturaATR() {
        return new Facturas.FacturaATR.DatosGeneralesFacturaATR.DatosFacturaATR();
    }

    /**
     * Create an instance of {@link MensajeFacturacion }
     * 
     */
    public MensajeFacturacion createMensajeFacturacion() {
        return new MensajeFacturacion();
    }

    /**
     * Create an instance of {@link Cabecera }
     * 
     */
    public Cabecera createCabecera() {
        return new Cabecera();
    }

    /**
     * Create an instance of {@link OtrosDatosFactura }
     * 
     */
    public OtrosDatosFactura createOtrosDatosFactura() {
        return new OtrosDatosFactura();
    }

    /**
     * Create an instance of {@link RegistroValAnomalias }
     * 
     */
    public RegistroValAnomalias createRegistroValAnomalias() {
        return new RegistroValAnomalias();
    }

    /**
     * Create an instance of {@link ContactoConDireccion }
     * 
     */
    public ContactoConDireccion createContactoConDireccion() {
        return new ContactoConDireccion();
    }

    /**
     * Create an instance of {@link RegistrosDocs }
     * 
     */
    public RegistrosDocs createRegistrosDocs() {
        return new RegistrosDocs();
    }

    /**
     * Create an instance of {@link ClienteConDireccion }
     * 
     */
    public ClienteConDireccion createClienteConDireccion() {
        return new ClienteConDireccion();
    }

    /**
     * Create an instance of {@link RegistroDoc }
     * 
     */
    public RegistroDoc createRegistroDoc() {
        return new RegistroDoc();
    }

    /**
     * Create an instance of {@link DatosReclamacionFactura }
     * 
     */
    public DatosReclamacionFactura createDatosReclamacionFactura() {
        return new DatosReclamacionFactura();
    }

    /**
     * Create an instance of {@link Medida }
     * 
     */
    public Medida createMedida() {
        return new Medida();
    }

    /**
     * Create an instance of {@link ContratoPasoMRAMLTarifa2SinCambios }
     * 
     */
    public ContratoPasoMRAMLTarifa2SinCambios createContratoPasoMRAMLTarifa2SinCambios() {
        return new ContratoPasoMRAMLTarifa2SinCambios();
    }

    /**
     * Create an instance of {@link ModelosAparato }
     * 
     */
    public ModelosAparato createModelosAparato() {
        return new ModelosAparato();
    }

    /**
     * Create an instance of {@link TipoLimiteIntervaloLectura }
     * 
     */
    public TipoLimiteIntervaloLectura createTipoLimiteIntervaloLectura() {
        return new TipoLimiteIntervaloLectura();
    }

    /**
     * Create an instance of {@link DatosCIE }
     * 
     */
    public DatosCIE createDatosCIE() {
        return new DatosCIE();
    }

    /**
     * Create an instance of {@link TipoDireccionSuministro }
     * 
     */
    public TipoDireccionSuministro createTipoDireccionSuministro() {
        return new TipoDireccionSuministro();
    }

    /**
     * Create an instance of {@link DireccionCorrespondencia }
     * 
     */
    public DireccionCorrespondencia createDireccionCorrespondencia() {
        return new DireccionCorrespondencia();
    }

    /**
     * Create an instance of {@link CondicionesContractualesD }
     * 
     */
    public CondicionesContractualesD createCondicionesContractualesD() {
        return new CondicionesContractualesD();
    }

    /**
     * Create an instance of {@link CondicionesContractualesC }
     * 
     */
    public CondicionesContractualesC createCondicionesContractualesC() {
        return new CondicionesContractualesC();
    }

    /**
     * Create an instance of {@link IdYNombreCliente }
     * 
     */
    public IdYNombreCliente createIdYNombreCliente() {
        return new IdYNombreCliente();
    }

    /**
     * Create an instance of {@link TipoDatosGeneralesFactura }
     * 
     */
    public TipoDatosGeneralesFactura createTipoDatosGeneralesFactura() {
        return new TipoDatosGeneralesFactura();
    }

    /**
     * Create an instance of {@link PuntoDeMedida }
     * 
     */
    public PuntoDeMedida createPuntoDeMedida() {
        return new PuntoDeMedida();
    }

    /**
     * Create an instance of {@link DatosAPM }
     * 
     */
    public DatosAPM createDatosAPM() {
        return new DatosAPM();
    }

    /**
     * Create an instance of {@link DireccionSinCodPostal }
     * 
     */
    public DireccionSinCodPostal createDireccionSinCodPostal() {
        return new DireccionSinCodPostal();
    }

    /**
     * Create an instance of {@link MedidaC2 }
     * 
     */
    public MedidaC2 createMedidaC2() {
        return new MedidaC2();
    }

    /**
     * Create an instance of {@link CondicionesContractuales }
     * 
     */
    public CondicionesContractuales createCondicionesContractuales() {
        return new CondicionesContractuales();
    }

    /**
     * Create an instance of {@link MedidasAparato }
     * 
     */
    public MedidasAparato createMedidasAparato() {
        return new MedidasAparato();
    }

    /**
     * Create an instance of {@link NombreCliente }
     * 
     */
    public NombreCliente createNombreCliente() {
        return new NombreCliente();
    }

    /**
     * Create an instance of {@link Reclamante }
     * 
     */
    public Reclamante createReclamante() {
        return new Reclamante();
    }

    /**
     * Create an instance of {@link DatosAceptacion }
     * 
     */
    public DatosAceptacion createDatosAceptacion() {
        return new DatosAceptacion();
    }

    /**
     * Create an instance of {@link DatosAparatoICP }
     * 
     */
    public DatosAparatoICP createDatosAparatoICP() {
        return new DatosAparatoICP();
    }

    /**
     * Create an instance of {@link Comentarios }
     * 
     */
    public Comentarios createComentarios() {
        return new Comentarios();
    }

    /**
     * Create an instance of {@link MedidaAparato }
     * 
     */
    public MedidaAparato createMedidaAparato() {
        return new MedidaAparato();
    }

    /**
     * Create an instance of {@link Contrato }
     * 
     */
    public Contrato createContrato() {
        return new Contrato();
    }

    /**
     * Create an instance of {@link CondicionesContractuales2N }
     * 
     */
    public CondicionesContractuales2N createCondicionesContractuales2N() {
        return new CondicionesContractuales2N();
    }

    /**
     * Create an instance of {@link ContratoPasoMRAMLTarifa2ConCambios }
     * 
     */
    public ContratoPasoMRAMLTarifa2ConCambios createContratoPasoMRAMLTarifa2ConCambios() {
        return new ContratoPasoMRAMLTarifa2ConCambios();
    }

    /**
     * Create an instance of {@link ClienteSinTelefono }
     * 
     */
    public ClienteSinTelefono createClienteSinTelefono() {
        return new ClienteSinTelefono();
    }

    /**
     * Create an instance of {@link CuentaBancaria }
     * 
     */
    public CuentaBancaria createCuentaBancaria() {
        return new CuentaBancaria();
    }

    /**
     * Create an instance of {@link ContratoConModificacion }
     * 
     */
    public ContratoConModificacion createContratoConModificacion() {
        return new ContratoConModificacion();
    }

    /**
     * Create an instance of {@link ModeloAparato }
     * 
     */
    public ModeloAparato createModeloAparato() {
        return new ModeloAparato();
    }

    /**
     * Create an instance of {@link MedidaResto }
     * 
     */
    public MedidaResto createMedidaResto() {
        return new MedidaResto();
    }

    /**
     * Create an instance of {@link DatosReclamacion }
     * 
     */
    public DatosReclamacion createDatosReclamacion() {
        return new DatosReclamacion();
    }

    /**
     * Create an instance of {@link IdCliente }
     * 
     */
    public IdCliente createIdCliente() {
        return new IdCliente();
    }

    /**
     * Create an instance of {@link DocTecnica }
     * 
     */
    public DocTecnica createDocTecnica() {
        return new DocTecnica();
    }

    /**
     * Create an instance of {@link CIEPapel }
     * 
     */
    public CIEPapel createCIEPapel() {
        return new CIEPapel();
    }

    /**
     * Create an instance of {@link Comentario }
     * 
     */
    public Comentario createComentario() {
        return new Comentario();
    }

    /**
     * Create an instance of {@link Contacto }
     * 
     */
    public Contacto createContacto() {
        return new Contacto();
    }

    /**
     * Create an instance of {@link TelefonoInternacional }
     * 
     */
    public TelefonoInternacional createTelefonoInternacional() {
        return new TelefonoInternacional();
    }

    /**
     * Create an instance of {@link DatosAparatoNoICP }
     * 
     */
    public DatosAparatoNoICP createDatosAparatoNoICP() {
        return new DatosAparatoNoICP();
    }

    /**
     * Create an instance of {@link RegistrosValAnomalias }
     * 
     */
    public RegistrosValAnomalias createRegistrosValAnomalias() {
        return new RegistrosValAnomalias();
    }

    /**
     * Create an instance of {@link ComentariosPM }
     * 
     */
    public ComentariosPM createComentariosPM() {
        return new ComentariosPM();
    }

    /**
     * Create an instance of {@link ComentarioPM }
     * 
     */
    public ComentarioPM createComentarioPM() {
        return new ComentarioPM();
    }

    /**
     * Create an instance of {@link com.eon.jaxb.Anomalia }
     * 
     */
    public com.eon.jaxb.Anomalia createAnomalia() {
        return new com.eon.jaxb.Anomalia();
    }

    /**
     * Create an instance of {@link ModeloAparatoAutolecturas }
     * 
     */
    public ModeloAparatoAutolecturas createModeloAparatoAutolecturas() {
        return new ModeloAparatoAutolecturas();
    }

    /**
     * Create an instance of {@link IdReclamante }
     * 
     */
    public IdReclamante createIdReclamante() {
        return new IdReclamante();
    }

    /**
     * Create an instance of {@link Importes }
     * 
     */
    public Importes createImportes() {
        return new Importes();
    }

    /**
     * Create an instance of {@link Direccion }
     * 
     */
    public Direccion createDireccion() {
        return new Direccion();
    }

    /**
     * Create an instance of {@link PuntosDeMedida }
     * 
     */
    public PuntosDeMedida createPuntosDeMedida() {
        return new PuntosDeMedida();
    }

    /**
     * Create an instance of {@link DatosAutolecturas }
     * 
     */
    public DatosAutolecturas createDatosAutolecturas() {
        return new DatosAutolecturas();
    }

    /**
     * Create an instance of {@link Cliente }
     * 
     */
    public Cliente createCliente() {
        return new Cliente();
    }

    /**
     * Create an instance of {@link DatosTitular }
     * 
     */
    public DatosTitular createDatosTitular() {
        return new DatosTitular();
    }

    /**
     * Create an instance of {@link com.eon.jaxb.Aparato }
     * 
     */
    public com.eon.jaxb.Aparato createAparato() {
        return new com.eon.jaxb.Aparato();
    }

    /**
     * Create an instance of {@link Aparatos }
     * 
     */
    public Aparatos createAparatos() {
        return new Aparatos();
    }

    /**
     * Create an instance of {@link IdContrato }
     * 
     */
    public IdContrato createIdContrato() {
        return new IdContrato();
    }

    /**
     * Create an instance of {@link TipoIVAIGIC }
     * 
     */
    public TipoIVAIGIC createTipoIVAIGIC() {
        return new TipoIVAIGIC();
    }

    /**
     * Create an instance of {@link RegistroAutolecturas }
     * 
     */
    public RegistroAutolecturas createRegistroAutolecturas() {
        return new RegistroAutolecturas();
    }

    /**
     * Create an instance of {@link DatosReclamante }
     * 
     */
    public DatosReclamante createDatosReclamante() {
        return new DatosReclamante();
    }

    /**
     * Create an instance of {@link Anomalias }
     * 
     */
    public Anomalias createAnomalias() {
        return new Anomalias();
    }

    /**
     * Create an instance of {@link CIEElectronico }
     * 
     */
    public CIEElectronico createCIEElectronico() {
        return new CIEElectronico();
    }

    /**
     * Create an instance of {@link EnergiasAFacturar.EnergiaAFacturar }
     * 
     */
    public EnergiasAFacturar.EnergiaAFacturar createEnergiasAFacturarEnergiaAFacturar() {
        return new EnergiasAFacturar.EnergiaAFacturar();
    }

    /**
     * Create an instance of {@link ReactivasAFacturar.ReactivaAFacturar }
     * 
     */
    public ReactivasAFacturar.ReactivaAFacturar createReactivasAFacturarReactivaAFacturar() {
        return new ReactivasAFacturar.ReactivaAFacturar();
    }

    /**
     * Create an instance of {@link ExcesosPotAFacturar.ExcesoPotAFacturar }
     * 
     */
    public ExcesosPotAFacturar.ExcesoPotAFacturar createExcesosPotAFacturarExcesoPotAFacturar() {
        return new ExcesosPotAFacturar.ExcesoPotAFacturar();
    }

    /**
     * Create an instance of {@link OtrosConceptos.Concepto }
     * 
     */
    public OtrosConceptos.Concepto createOtrosConceptosConcepto() {
        return new OtrosConceptos.Concepto();
    }

    /**
     * Create an instance of {@link PotenciasAFacturar.PotenciaAFacturar }
     * 
     */
    public PotenciasAFacturar.PotenciaAFacturar createPotenciasAFacturarPotenciaAFacturar() {
        return new PotenciasAFacturar.PotenciaAFacturar();
    }

    /**
     * Create an instance of {@link ImportesTerminoEnergia.ImporteTerminoEnergia }
     * 
     */
    public ImportesTerminoEnergia.ImporteTerminoEnergia createImportesTerminoEnergiaImporteTerminoEnergia() {
        return new ImportesTerminoEnergia.ImporteTerminoEnergia();
    }

    /**
     * Create an instance of {@link Potencias.Potencia }
     * 
     */
    public Potencias.Potencia createPotenciasPotencia() {
        return new Potencias.Potencia();
    }

    /**
     * Create an instance of {@link ImportesOtrosConceptos.ImporteOtrosConceptos }
     * 
     */
    public ImportesOtrosConceptos.ImporteOtrosConceptos createImportesOtrosConceptosImporteOtrosConceptos() {
        return new ImportesOtrosConceptos.ImporteOtrosConceptos();
    }

    /**
     * Create an instance of {@link ImportesTerminoPotencia.ImporteTerminoPotencia }
     * 
     */
    public ImportesTerminoPotencia.ImporteTerminoPotencia createImportesTerminoPotenciaImporteTerminoPotencia() {
        return new ImportesTerminoPotencia.ImporteTerminoPotencia();
    }

    /**
     * Create an instance of {@link Facturas.RegistroFin }
     * 
     */
    public Facturas.RegistroFin createFacturasRegistroFin() {
        return new Facturas.RegistroFin();
    }

    /**
     * Create an instance of {@link Facturas.OtrasFacturas.DatosGeneralesOtrasFacturas }
     * 
     */
    public Facturas.OtrasFacturas.DatosGeneralesOtrasFacturas createFacturasOtrasFacturasDatosGeneralesOtrasFacturas() {
        return new Facturas.OtrasFacturas.DatosGeneralesOtrasFacturas();
    }

    /**
     * Create an instance of {@link Facturas.OtrasFacturas.Concepto }
     * 
     */
    public Facturas.OtrasFacturas.Concepto createFacturasOtrasFacturasConcepto() {
        return new Facturas.OtrasFacturas.Concepto();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.ConceptoIEIVA }
     * 
     */
    public Facturas.FacturaATR.ConceptoIEIVA createFacturasFacturaATRConceptoIEIVA() {
        return new Facturas.FacturaATR.ConceptoIEIVA();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.ImpuestoElectrico }
     * 
     */
    public Facturas.FacturaATR.ImpuestoElectrico createFacturasFacturaATRImpuestoElectrico() {
        return new Facturas.FacturaATR.ImpuestoElectrico();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Alquileres }
     * 
     */
    public Facturas.FacturaATR.Alquileres createFacturasFacturaATRAlquileres() {
        return new Facturas.FacturaATR.Alquileres();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.ConceptoIVA }
     * 
     */
    public Facturas.FacturaATR.ConceptoIVA createFacturasFacturaATRConceptoIVA() {
        return new Facturas.FacturaATR.ConceptoIVA();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Medidas.Aparato.Integrador.Ajuste }
     * 
     */
    public Facturas.FacturaATR.Medidas.Aparato.Integrador.Ajuste createFacturasFacturaATRMedidasAparatoIntegradorAjuste() {
        return new Facturas.FacturaATR.Medidas.Aparato.Integrador.Ajuste();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Medidas.Aparato.Integrador.Anomalia }
     * 
     */
    public Facturas.FacturaATR.Medidas.Aparato.Integrador.Anomalia createFacturasFacturaATRMedidasAparatoIntegradorAnomalia() {
        return new Facturas.FacturaATR.Medidas.Aparato.Integrador.Anomalia();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Refacturaciones.Refacturacion }
     * 
     */
    public Facturas.FacturaATR.Refacturaciones.Refacturacion createFacturasFacturaATRRefacturacionesRefacturacion() {
        return new Facturas.FacturaATR.Refacturaciones.Refacturacion();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.EnergiaReactiva.TerminoEnergiaReactiva.Periodo }
     * 
     */
    public Facturas.FacturaATR.EnergiaReactiva.TerminoEnergiaReactiva.Periodo createFacturasFacturaATREnergiaReactivaTerminoEnergiaReactivaPeriodo() {
        return new Facturas.FacturaATR.EnergiaReactiva.TerminoEnergiaReactiva.Periodo();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.EnergiaActiva.TerminoEnergiaActiva.Periodo }
     * 
     */
    public Facturas.FacturaATR.EnergiaActiva.TerminoEnergiaActiva.Periodo createFacturasFacturaATREnergiaActivaTerminoEnergiaActivaPeriodo() {
        return new Facturas.FacturaATR.EnergiaActiva.TerminoEnergiaActiva.Periodo();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.ExcesoPotencia.Periodo }
     * 
     */
    public Facturas.FacturaATR.ExcesoPotencia.Periodo createFacturasFacturaATRExcesoPotenciaPeriodo() {
        return new Facturas.FacturaATR.ExcesoPotencia.Periodo();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.Potencia.TerminoPotencia.Periodo }
     * 
     */
    public Facturas.FacturaATR.Potencia.TerminoPotencia.Periodo createFacturasFacturaATRPotenciaTerminoPotenciaPeriodo() {
        return new Facturas.FacturaATR.Potencia.TerminoPotencia.Periodo();
    }

    /**
     * Create an instance of {@link Facturas.FacturaATR.DatosGeneralesFacturaATR.DatosFacturaATR.Periodo }
     * 
     */
    public Facturas.FacturaATR.DatosGeneralesFacturaATR.DatosFacturaATR.Periodo createFacturasFacturaATRDatosGeneralesFacturaATRDatosFacturaATRPeriodo() {
        return new Facturas.FacturaATR.DatosGeneralesFacturaATR.DatosFacturaATR.Periodo();
    }

}
