//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtrosDatosFactura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtrosDatosFactura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SociedadMercantilEmisora">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SociedadMercantilDestino">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DireccionEmisora">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DireccionDestino">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtrosDatosFactura", propOrder = {
    "sociedadMercantilEmisora",
    "sociedadMercantilDestino",
    "direccionEmisora",
    "direccionDestino"
})
public class OtrosDatosFactura {

    @XmlElement(name = "SociedadMercantilEmisora", required = true)
    protected String sociedadMercantilEmisora;
    @XmlElement(name = "SociedadMercantilDestino", required = true)
    protected String sociedadMercantilDestino;
    @XmlElement(name = "DireccionEmisora", required = true)
    protected String direccionEmisora;
    @XmlElement(name = "DireccionDestino", required = true)
    protected String direccionDestino;

    /**
     * Gets the value of the sociedadMercantilEmisora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSociedadMercantilEmisora() {
        return sociedadMercantilEmisora;
    }

    /**
     * Sets the value of the sociedadMercantilEmisora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSociedadMercantilEmisora(String value) {
        this.sociedadMercantilEmisora = value;
    }

    /**
     * Gets the value of the sociedadMercantilDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSociedadMercantilDestino() {
        return sociedadMercantilDestino;
    }

    /**
     * Sets the value of the sociedadMercantilDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSociedadMercantilDestino(String value) {
        this.sociedadMercantilDestino = value;
    }

    /**
     * Gets the value of the direccionEmisora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionEmisora() {
        return direccionEmisora;
    }

    /**
     * Sets the value of the direccionEmisora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionEmisora(String value) {
        this.direccionEmisora = value;
    }

    /**
     * Gets the value of the direccionDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionDestino() {
        return direccionDestino;
    }

    /**
     * Sets the value of the direccionDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionDestino(String value) {
        this.direccionDestino = value;
    }

}
