//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PuntoDeMedida complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PuntoDeMedida">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodPM" type="{http://localhost/elegibilidad}CodPM"/>
 *         &lt;element name="TipoMovimiento" type="{http://localhost/elegibilidad}AltaBajaModificacion"/>
 *         &lt;element name="CodREE" type="{http://localhost/elegibilidad}X8" minOccurs="0"/>
 *         &lt;element name="CUPS" type="{http://localhost/elegibilidad}CUPS"/>
 *         &lt;element name="TipoPM" type="{http://localhost/elegibilidad}TipoPM"/>
 *         &lt;element name="CodPMPrincipal" type="{http://localhost/elegibilidad}CodPM" minOccurs="0"/>
 *         &lt;element name="ModoLectura" type="{http://localhost/elegibilidad}ModoLecturaPM"/>
 *         &lt;element name="EstadoPM" type="{http://localhost/elegibilidad}EstadoPM"/>
 *         &lt;element name="Funcion" type="{http://localhost/elegibilidad}FuncionPM"/>
 *         &lt;element name="DireccionEnlace" type="{http://localhost/elegibilidad}X10" minOccurs="0"/>
 *         &lt;element name="DireccionPuntoMedida" type="{http://localhost/elegibilidad}X10" minOccurs="0"/>
 *         &lt;element name="NumLinea" type="{http://localhost/elegibilidad}Decimal2" minOccurs="0"/>
 *         &lt;element name="TelefonoTelemedida" type="{http://localhost/elegibilidad}Decimal9" minOccurs="0"/>
 *         &lt;element name="EstadoTelefono" type="{http://localhost/elegibilidad}EstadoTelefono" minOccurs="0"/>
 *         &lt;element name="ClaveAcceso" type="{http://localhost/elegibilidad}X10" minOccurs="0"/>
 *         &lt;element name="TensionPM" type="{http://localhost/elegibilidad}Decimal9" minOccurs="0"/>
 *         &lt;element name="FechaVigor" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FechaAlta" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FechaBaja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PasswordPM" type="{http://localhost/elegibilidad}X10" minOccurs="0"/>
 *         &lt;element name="Aparatos" type="{http://localhost/elegibilidad}Aparatos" minOccurs="0"/>
 *         &lt;element name="ComentariosPM" type="{http://localhost/elegibilidad}ComentariosPM" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PuntoDeMedida", propOrder = {
    "codPM",
    "tipoMovimiento",
    "codREE",
    "cups",
    "tipoPM",
    "codPMPrincipal",
    "modoLectura",
    "estadoPM",
    "funcion",
    "direccionEnlace",
    "direccionPuntoMedida",
    "numLinea",
    "telefonoTelemedida",
    "estadoTelefono",
    "claveAcceso",
    "tensionPM",
    "fechaVigor",
    "fechaAlta",
    "fechaBaja",
    "passwordPM",
    "aparatos",
    "comentariosPM"
})
public class PuntoDeMedida {

    @XmlElement(name = "CodPM", required = true)
    protected String codPM;
    @XmlElement(name = "TipoMovimiento", required = true)
    protected String tipoMovimiento;
    @XmlElement(name = "CodREE")
    protected String codREE;
    @XmlElement(name = "CUPS", required = true)
    protected String cups;
    @XmlElement(name = "TipoPM", required = true)
    protected String tipoPM;
    @XmlElement(name = "CodPMPrincipal")
    protected String codPMPrincipal;
    @XmlElement(name = "ModoLectura", required = true)
    protected String modoLectura;
    @XmlElement(name = "EstadoPM", required = true)
    protected String estadoPM;
    @XmlElement(name = "Funcion", required = true)
    protected FuncionPM funcion;
    @XmlElement(name = "DireccionEnlace")
    protected String direccionEnlace;
    @XmlElement(name = "DireccionPuntoMedida")
    protected String direccionPuntoMedida;
    @XmlElement(name = "NumLinea")
    protected BigInteger numLinea;
    @XmlElement(name = "TelefonoTelemedida")
    protected Long telefonoTelemedida;
    @XmlElement(name = "EstadoTelefono")
    protected String estadoTelefono;
    @XmlElement(name = "ClaveAcceso")
    protected String claveAcceso;
    @XmlElement(name = "TensionPM")
    protected Long tensionPM;
    @XmlElement(name = "FechaVigor", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaVigor;
    @XmlElement(name = "FechaAlta", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaAlta;
    @XmlElement(name = "FechaBaja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaBaja;
    @XmlElement(name = "PasswordPM")
    protected String passwordPM;
    @XmlElement(name = "Aparatos")
    protected Aparatos aparatos;
    @XmlElement(name = "ComentariosPM")
    protected ComentariosPM comentariosPM;

    /**
     * Gets the value of the codPM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPM() {
        return codPM;
    }

    /**
     * Sets the value of the codPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPM(String value) {
        this.codPM = value;
    }

    /**
     * Gets the value of the tipoMovimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoMovimiento() {
        return tipoMovimiento;
    }

    /**
     * Sets the value of the tipoMovimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoMovimiento(String value) {
        this.tipoMovimiento = value;
    }

    /**
     * Gets the value of the codREE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodREE() {
        return codREE;
    }

    /**
     * Sets the value of the codREE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodREE(String value) {
        this.codREE = value;
    }

    /**
     * Gets the value of the cups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUPS() {
        return cups;
    }

    /**
     * Sets the value of the cups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUPS(String value) {
        this.cups = value;
    }

    /**
     * Gets the value of the tipoPM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPM() {
        return tipoPM;
    }

    /**
     * Sets the value of the tipoPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPM(String value) {
        this.tipoPM = value;
    }

    /**
     * Gets the value of the codPMPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPMPrincipal() {
        return codPMPrincipal;
    }

    /**
     * Sets the value of the codPMPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPMPrincipal(String value) {
        this.codPMPrincipal = value;
    }

    /**
     * Gets the value of the modoLectura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModoLectura() {
        return modoLectura;
    }

    /**
     * Sets the value of the modoLectura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModoLectura(String value) {
        this.modoLectura = value;
    }

    /**
     * Gets the value of the estadoPM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoPM() {
        return estadoPM;
    }

    /**
     * Sets the value of the estadoPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoPM(String value) {
        this.estadoPM = value;
    }

    /**
     * Gets the value of the funcion property.
     * 
     * @return
     *     possible object is
     *     {@link FuncionPM }
     *     
     */
    public FuncionPM getFuncion() {
        return funcion;
    }

    /**
     * Sets the value of the funcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuncionPM }
     *     
     */
    public void setFuncion(FuncionPM value) {
        this.funcion = value;
    }

    /**
     * Gets the value of the direccionEnlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionEnlace() {
        return direccionEnlace;
    }

    /**
     * Sets the value of the direccionEnlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionEnlace(String value) {
        this.direccionEnlace = value;
    }

    /**
     * Gets the value of the direccionPuntoMedida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionPuntoMedida() {
        return direccionPuntoMedida;
    }

    /**
     * Sets the value of the direccionPuntoMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionPuntoMedida(String value) {
        this.direccionPuntoMedida = value;
    }

    /**
     * Gets the value of the numLinea property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumLinea() {
        return numLinea;
    }

    /**
     * Sets the value of the numLinea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumLinea(BigInteger value) {
        this.numLinea = value;
    }

    /**
     * Gets the value of the telefonoTelemedida property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTelefonoTelemedida() {
        return telefonoTelemedida;
    }

    /**
     * Sets the value of the telefonoTelemedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTelefonoTelemedida(Long value) {
        this.telefonoTelemedida = value;
    }

    /**
     * Gets the value of the estadoTelefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoTelefono() {
        return estadoTelefono;
    }

    /**
     * Sets the value of the estadoTelefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoTelefono(String value) {
        this.estadoTelefono = value;
    }

    /**
     * Gets the value of the claveAcceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveAcceso() {
        return claveAcceso;
    }

    /**
     * Sets the value of the claveAcceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveAcceso(String value) {
        this.claveAcceso = value;
    }

    /**
     * Gets the value of the tensionPM property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTensionPM() {
        return tensionPM;
    }

    /**
     * Sets the value of the tensionPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTensionPM(Long value) {
        this.tensionPM = value;
    }

    /**
     * Gets the value of the fechaVigor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaVigor() {
        return fechaVigor;
    }

    /**
     * Sets the value of the fechaVigor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaVigor(XMLGregorianCalendar value) {
        this.fechaVigor = value;
    }

    /**
     * Gets the value of the fechaAlta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaAlta() {
        return fechaAlta;
    }

    /**
     * Sets the value of the fechaAlta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaAlta(XMLGregorianCalendar value) {
        this.fechaAlta = value;
    }

    /**
     * Gets the value of the fechaBaja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaBaja() {
        return fechaBaja;
    }

    /**
     * Sets the value of the fechaBaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaBaja(XMLGregorianCalendar value) {
        this.fechaBaja = value;
    }

    /**
     * Gets the value of the passwordPM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordPM() {
        return passwordPM;
    }

    /**
     * Sets the value of the passwordPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordPM(String value) {
        this.passwordPM = value;
    }

    /**
     * Gets the value of the aparatos property.
     * 
     * @return
     *     possible object is
     *     {@link Aparatos }
     *     
     */
    public Aparatos getAparatos() {
        return aparatos;
    }

    /**
     * Sets the value of the aparatos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aparatos }
     *     
     */
    public void setAparatos(Aparatos value) {
        this.aparatos = value;
    }

    /**
     * Gets the value of the comentariosPM property.
     * 
     * @return
     *     possible object is
     *     {@link ComentariosPM }
     *     
     */
    public ComentariosPM getComentariosPM() {
        return comentariosPM;
    }

    /**
     * Sets the value of the comentariosPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComentariosPM }
     *     
     */
    public void setComentariosPM(ComentariosPM value) {
        this.comentariosPM = value;
    }

}
