//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PuntosDeMedida complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PuntosDeMedida">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PuntoDeMedida" type="{http://localhost/elegibilidad}PuntoDeMedida" maxOccurs="10"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PuntosDeMedida", propOrder = {
    "puntoDeMedida"
})
public class PuntosDeMedida {

    @XmlElement(name = "PuntoDeMedida", required = true)
    protected List<PuntoDeMedida> puntoDeMedida;

    /**
     * Gets the value of the puntoDeMedida property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the puntoDeMedida property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPuntoDeMedida().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PuntoDeMedida }
     * 
     * 
     */
    public List<PuntoDeMedida> getPuntoDeMedida() {
        if (puntoDeMedida == null) {
            puntoDeMedida = new ArrayList<PuntoDeMedida>();
        }
        return this.puntoDeMedida;
    }

}
