//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RegistroValAnomalias complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroValAnomalias">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InicioRefacturacion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FinRefacturacion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FechaDesdeHistorico" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FechaHastaHistorico" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CodigoTarifa" type="{http://localhost/elegibilidad}Tarifa" minOccurs="0"/>
 *         &lt;element name="Potencias" type="{http://localhost/elegibilidad}PotenciasAFacturar" minOccurs="0"/>
 *         &lt;element name="Energias" type="{http://localhost/elegibilidad}EnergiasAFacturar" minOccurs="0"/>
 *         &lt;element name="Reactivas" type="{http://localhost/elegibilidad}ReactivasAFacturar" minOccurs="0"/>
 *         &lt;element name="ExcesosPotencia" type="{http://localhost/elegibilidad}ExcesosPotAFacturar" minOccurs="0"/>
 *         &lt;element name="OtrosConceptos" type="{http://localhost/elegibilidad}OtrosConceptos" minOccurs="0"/>
 *         &lt;element name="Importes" type="{http://localhost/elegibilidad}Importes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroValAnomalias", propOrder = {
    "inicioRefacturacion",
    "finRefacturacion",
    "fechaDesdeHistorico",
    "fechaHastaHistorico",
    "codigoTarifa",
    "potencias",
    "energias",
    "reactivas",
    "excesosPotencia",
    "otrosConceptos",
    "importes"
})
public class RegistroValAnomalias {

    @XmlElement(name = "InicioRefacturacion", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar inicioRefacturacion;
    @XmlElement(name = "FinRefacturacion", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar finRefacturacion;
    @XmlElement(name = "FechaDesdeHistorico")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaDesdeHistorico;
    @XmlElement(name = "FechaHastaHistorico")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaHastaHistorico;
    @XmlElement(name = "CodigoTarifa")
    protected String codigoTarifa;
    @XmlElement(name = "Potencias")
    protected PotenciasAFacturar potencias;
    @XmlElement(name = "Energias")
    protected EnergiasAFacturar energias;
    @XmlElement(name = "Reactivas")
    protected ReactivasAFacturar reactivas;
    @XmlElement(name = "ExcesosPotencia")
    protected ExcesosPotAFacturar excesosPotencia;
    @XmlElement(name = "OtrosConceptos")
    protected OtrosConceptos otrosConceptos;
    @XmlElement(name = "Importes")
    protected Importes importes;

    /**
     * Gets the value of the inicioRefacturacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInicioRefacturacion() {
        return inicioRefacturacion;
    }

    /**
     * Sets the value of the inicioRefacturacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInicioRefacturacion(XMLGregorianCalendar value) {
        this.inicioRefacturacion = value;
    }

    /**
     * Gets the value of the finRefacturacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinRefacturacion() {
        return finRefacturacion;
    }

    /**
     * Sets the value of the finRefacturacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinRefacturacion(XMLGregorianCalendar value) {
        this.finRefacturacion = value;
    }

    /**
     * Gets the value of the fechaDesdeHistorico property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaDesdeHistorico() {
        return fechaDesdeHistorico;
    }

    /**
     * Sets the value of the fechaDesdeHistorico property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaDesdeHistorico(XMLGregorianCalendar value) {
        this.fechaDesdeHistorico = value;
    }

    /**
     * Gets the value of the fechaHastaHistorico property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaHastaHistorico() {
        return fechaHastaHistorico;
    }

    /**
     * Sets the value of the fechaHastaHistorico property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaHastaHistorico(XMLGregorianCalendar value) {
        this.fechaHastaHistorico = value;
    }

    /**
     * Gets the value of the codigoTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTarifa() {
        return codigoTarifa;
    }

    /**
     * Sets the value of the codigoTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTarifa(String value) {
        this.codigoTarifa = value;
    }

    /**
     * Gets the value of the potencias property.
     * 
     * @return
     *     possible object is
     *     {@link PotenciasAFacturar }
     *     
     */
    public PotenciasAFacturar getPotencias() {
        return potencias;
    }

    /**
     * Sets the value of the potencias property.
     * 
     * @param value
     *     allowed object is
     *     {@link PotenciasAFacturar }
     *     
     */
    public void setPotencias(PotenciasAFacturar value) {
        this.potencias = value;
    }

    /**
     * Gets the value of the energias property.
     * 
     * @return
     *     possible object is
     *     {@link EnergiasAFacturar }
     *     
     */
    public EnergiasAFacturar getEnergias() {
        return energias;
    }

    /**
     * Sets the value of the energias property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergiasAFacturar }
     *     
     */
    public void setEnergias(EnergiasAFacturar value) {
        this.energias = value;
    }

    /**
     * Gets the value of the reactivas property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivasAFacturar }
     *     
     */
    public ReactivasAFacturar getReactivas() {
        return reactivas;
    }

    /**
     * Sets the value of the reactivas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivasAFacturar }
     *     
     */
    public void setReactivas(ReactivasAFacturar value) {
        this.reactivas = value;
    }

    /**
     * Gets the value of the excesosPotencia property.
     * 
     * @return
     *     possible object is
     *     {@link ExcesosPotAFacturar }
     *     
     */
    public ExcesosPotAFacturar getExcesosPotencia() {
        return excesosPotencia;
    }

    /**
     * Sets the value of the excesosPotencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcesosPotAFacturar }
     *     
     */
    public void setExcesosPotencia(ExcesosPotAFacturar value) {
        this.excesosPotencia = value;
    }

    /**
     * Gets the value of the otrosConceptos property.
     * 
     * @return
     *     possible object is
     *     {@link OtrosConceptos }
     *     
     */
    public OtrosConceptos getOtrosConceptos() {
        return otrosConceptos;
    }

    /**
     * Sets the value of the otrosConceptos property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtrosConceptos }
     *     
     */
    public void setOtrosConceptos(OtrosConceptos value) {
        this.otrosConceptos = value;
    }

    /**
     * Gets the value of the importes property.
     * 
     * @return
     *     possible object is
     *     {@link Importes }
     *     
     */
    public Importes getImportes() {
        return importes;
    }

    /**
     * Sets the value of the importes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Importes }
     *     
     */
    public void setImportes(Importes value) {
        this.importes = value;
    }

}
