//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegistroDoc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroDoc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoDocAportado" type="{http://localhost/elegibilidad}TiposDocumentacion" minOccurs="0"/>
 *         &lt;element name="DireccionUrl" type="{http://localhost/elegibilidad}X255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroDoc", propOrder = {
    "tipoDocAportado",
    "direccionUrl"
})
public class RegistroDoc {

    @XmlElement(name = "TipoDocAportado")
    protected String tipoDocAportado;
    @XmlElement(name = "DireccionUrl")
    protected String direccionUrl;

    /**
     * Gets the value of the tipoDocAportado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocAportado() {
        return tipoDocAportado;
    }

    /**
     * Sets the value of the tipoDocAportado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocAportado(String value) {
        this.tipoDocAportado = value;
    }

    /**
     * Gets the value of the direccionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionUrl() {
        return direccionUrl;
    }

    /**
     * Sets the value of the direccionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionUrl(String value) {
        this.direccionUrl = value;
    }

}
