//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoDireccionSuministro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoDireccionSuministro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUPS" type="{http://localhost/elegibilidad}CUPS"/>
 *         &lt;element name="Municipio" type="{http://localhost/elegibilidad}Decimal7"/>
 *         &lt;element name="DirSuministro">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDireccionSuministro", propOrder = {
    "cups",
    "municipio",
    "dirSuministro"
})
public class TipoDireccionSuministro {

    @XmlElement(name = "CUPS", required = true)
    protected String cups;
    @XmlElement(name = "Municipio")
    protected long municipio;
    @XmlElement(name = "DirSuministro", required = true)
    protected String dirSuministro;

    /**
     * Gets the value of the cups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUPS() {
        return cups;
    }

    /**
     * Sets the value of the cups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUPS(String value) {
        this.cups = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     */
    public long getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     */
    public void setMunicipio(long value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the dirSuministro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirSuministro() {
        return dirSuministro;
    }

    /**
     * Sets the value of the dirSuministro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirSuministro(String value) {
        this.dirSuministro = value;
    }

}
