//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TiposSuministro.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TiposSuministro">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="AS"/>
 *     &lt;enumeration value="AT"/>
 *     &lt;enumeration value="BA"/>
 *     &lt;enumeration value="CM"/>
 *     &lt;enumeration value="EA"/>
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="FT"/>
 *     &lt;enumeration value="FV"/>
 *     &lt;enumeration value="GA"/>
 *     &lt;enumeration value="GB"/>
 *     &lt;enumeration value="HP"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="KC"/>
 *     &lt;enumeration value="LB"/>
 *     &lt;enumeration value="LC"/>
 *     &lt;enumeration value="OF"/>
 *     &lt;enumeration value="PC"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="RT"/>
 *     &lt;enumeration value="SA"/>
 *     &lt;enumeration value="SC"/>
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="SG"/>
 *     &lt;enumeration value="SM"/>
 *     &lt;enumeration value="SO"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TR"/>
 *     &lt;enumeration value="UF"/>
 *     &lt;enumeration value="UV"/>
 *     &lt;enumeration value="VI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TiposSuministro")
@XmlEnum
public enum TiposSuministro {

    AL,
    AP,
    AS,
    AT,
    BA,
    CM,
    EA,
    ES,
    FT,
    FV,
    GA,
    GB,
    HP,
    IN,
    IT,
    KC,
    LB,
    LC,
    OF,
    PC,
    RA,
    RT,
    SA,
    SC,
    SE,
    SG,
    SM,
    SO,
    TL,
    TR,
    UF,
    UV,
    VI;

    public String value() {
        return name();
    }

    public static TiposSuministro fromValue(String v) {
        return valueOf(v);
    }

}
