//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoIdentificador.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoIdentificador">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="DN"/>
 *     &lt;enumeration value="NI"/>
 *     &lt;enumeration value="NV"/>
 *     &lt;enumeration value="OT"/>
 *     &lt;enumeration value="PS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoIdentificador")
@XmlEnum
public enum TipoIdentificador {

    CI,
    CT,
    DN,
    NI,
    NV,
    OT,
    PS;

    public String value() {
        return name();
    }

    public static TipoIdentificador fromValue(String v) {
        return valueOf(v);
    }

}
