//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoAparato.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoAparato">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BP"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="CG"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="IH"/>
 *     &lt;enumeration value="IP"/>
 *     &lt;enumeration value="MO"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="RG"/>
 *     &lt;enumeration value="RT"/>
 *     &lt;enumeration value="TA"/>
 *     &lt;enumeration value="TC"/>
 *     &lt;enumeration value="TI"/>
 *     &lt;enumeration value="TP"/>
 *     &lt;enumeration value="TT"/>
 *     &lt;enumeration value="ZZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoAparato")
@XmlEnum
public enum TipoAparato {

    BP,
    CA,
    CC,
    CG,
    CO,
    CR,
    CT,
    G,
    H,
    IH,
    IP,
    MO,
    P,
    RG,
    RT,
    TA,
    TC,
    TI,
    TP,
    TT,
    ZZ;

    public String value() {
        return name();
    }

    public static TipoAparato fromValue(String v) {
        return valueOf(v);
    }

}
