//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TipoDatosGeneralesFactura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoDatosGeneralesFactura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroFactura">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="26"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TipoFactura" type="{http://localhost/elegibilidad}TipoFactura"/>
 *         &lt;element name="IndicativoFacturaRectificadora" type="{http://localhost/elegibilidad}TipoFacturaRectificadora"/>
 *         &lt;element name="NumeroFacturaRectificada" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="26"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FechaFactura" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CIFEmisora">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CodigoFiscalFactura" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="17"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Observaciones" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ImporteTotalFactura">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="12"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SaldoFactura">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="12"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SaldoCobro">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="12"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TipoMoneda" type="{http://localhost/elegibilidad}TipoMoneda"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDatosGeneralesFactura", propOrder = {
    "numeroFactura",
    "tipoFactura",
    "indicativoFacturaRectificadora",
    "numeroFacturaRectificada",
    "fechaFactura",
    "cifEmisora",
    "codigoFiscalFactura",
    "observaciones",
    "importeTotalFactura",
    "saldoFactura",
    "saldoCobro",
    "tipoMoneda"
})
public class TipoDatosGeneralesFactura {

    @XmlElement(name = "NumeroFactura", required = true)
    protected String numeroFactura;
    @XmlElement(name = "TipoFactura", required = true)
    protected String tipoFactura;
    @XmlElement(name = "IndicativoFacturaRectificadora", required = true)
    protected TipoFacturaRectificadora indicativoFacturaRectificadora;
    @XmlElement(name = "NumeroFacturaRectificada")
    protected String numeroFacturaRectificada;
    @XmlElement(name = "FechaFactura", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaFactura;
    @XmlElement(name = "CIFEmisora", required = true)
    protected String cifEmisora;
    @XmlElement(name = "CodigoFiscalFactura")
    protected String codigoFiscalFactura;
    @XmlElement(name = "Observaciones")
    protected String observaciones;
    @XmlElement(name = "ImporteTotalFactura", required = true)
    protected BigDecimal importeTotalFactura;
    @XmlElement(name = "SaldoFactura", required = true)
    protected BigDecimal saldoFactura;
    @XmlElement(name = "SaldoCobro", required = true)
    protected BigDecimal saldoCobro;
    @XmlElement(name = "TipoMoneda", required = true)
    protected String tipoMoneda;

    /**
     * Gets the value of the numeroFactura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFactura() {
        return numeroFactura;
    }

    /**
     * Sets the value of the numeroFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFactura(String value) {
        this.numeroFactura = value;
    }

    /**
     * Gets the value of the tipoFactura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoFactura() {
        return tipoFactura;
    }

    /**
     * Sets the value of the tipoFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoFactura(String value) {
        this.tipoFactura = value;
    }

    /**
     * Gets the value of the indicativoFacturaRectificadora property.
     * 
     * @return
     *     possible object is
     *     {@link TipoFacturaRectificadora }
     *     
     */
    public TipoFacturaRectificadora getIndicativoFacturaRectificadora() {
        return indicativoFacturaRectificadora;
    }

    /**
     * Sets the value of the indicativoFacturaRectificadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoFacturaRectificadora }
     *     
     */
    public void setIndicativoFacturaRectificadora(TipoFacturaRectificadora value) {
        this.indicativoFacturaRectificadora = value;
    }

    /**
     * Gets the value of the numeroFacturaRectificada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFacturaRectificada() {
        return numeroFacturaRectificada;
    }

    /**
     * Sets the value of the numeroFacturaRectificada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFacturaRectificada(String value) {
        this.numeroFacturaRectificada = value;
    }

    /**
     * Gets the value of the fechaFactura property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaFactura() {
        return fechaFactura;
    }

    /**
     * Sets the value of the fechaFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaFactura(XMLGregorianCalendar value) {
        this.fechaFactura = value;
    }

    /**
     * Gets the value of the cifEmisora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIFEmisora() {
        return cifEmisora;
    }

    /**
     * Sets the value of the cifEmisora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIFEmisora(String value) {
        this.cifEmisora = value;
    }

    /**
     * Gets the value of the codigoFiscalFactura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoFiscalFactura() {
        return codigoFiscalFactura;
    }

    /**
     * Sets the value of the codigoFiscalFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoFiscalFactura(String value) {
        this.codigoFiscalFactura = value;
    }

    /**
     * Gets the value of the observaciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservaciones() {
        return observaciones;
    }

    /**
     * Sets the value of the observaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservaciones(String value) {
        this.observaciones = value;
    }

    /**
     * Gets the value of the importeTotalFactura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporteTotalFactura() {
        return importeTotalFactura;
    }

    /**
     * Sets the value of the importeTotalFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporteTotalFactura(BigDecimal value) {
        this.importeTotalFactura = value;
    }

    /**
     * Gets the value of the saldoFactura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoFactura() {
        return saldoFactura;
    }

    /**
     * Sets the value of the saldoFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoFactura(BigDecimal value) {
        this.saldoFactura = value;
    }

    /**
     * Gets the value of the saldoCobro property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoCobro() {
        return saldoCobro;
    }

    /**
     * Sets the value of the saldoCobro property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoCobro(BigDecimal value) {
        this.saldoCobro = value;
    }

    /**
     * Gets the value of the tipoMoneda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoMoneda() {
        return tipoMoneda;
    }

    /**
     * Sets the value of the tipoMoneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoMoneda(String value) {
        this.tipoMoneda = value;
    }

}
