//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoAnomalia.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoAnomalia">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A100"/>
 *     &lt;enumeration value="A101"/>
 *     &lt;enumeration value="A102"/>
 *     &lt;enumeration value="A103"/>
 *     &lt;enumeration value="A104"/>
 *     &lt;enumeration value="A105"/>
 *     &lt;enumeration value="A107"/>
 *     &lt;enumeration value="A108"/>
 *     &lt;enumeration value="A110"/>
 *     &lt;enumeration value="A111"/>
 *     &lt;enumeration value="A112"/>
 *     &lt;enumeration value="A115"/>
 *     &lt;enumeration value="A116"/>
 *     &lt;enumeration value="A117"/>
 *     &lt;enumeration value="A118"/>
 *     &lt;enumeration value="A119"/>
 *     &lt;enumeration value="A120"/>
 *     &lt;enumeration value="A121"/>
 *     &lt;enumeration value="A199"/>
 *     &lt;enumeration value="F200"/>
 *     &lt;enumeration value="F201"/>
 *     &lt;enumeration value="F202"/>
 *     &lt;enumeration value="F203"/>
 *     &lt;enumeration value="F204"/>
 *     &lt;enumeration value="F205"/>
 *     &lt;enumeration value="F206"/>
 *     &lt;enumeration value="F207"/>
 *     &lt;enumeration value="F208"/>
 *     &lt;enumeration value="F209"/>
 *     &lt;enumeration value="F210"/>
 *     &lt;enumeration value="F211"/>
 *     &lt;enumeration value="F212"/>
 *     &lt;enumeration value="F213"/>
 *     &lt;enumeration value="F214"/>
 *     &lt;enumeration value="F215"/>
 *     &lt;enumeration value="F216"/>
 *     &lt;enumeration value="F217"/>
 *     &lt;enumeration value="F218"/>
 *     &lt;enumeration value="F219"/>
 *     &lt;enumeration value="F220"/>
 *     &lt;enumeration value="F221"/>
 *     &lt;enumeration value="F222"/>
 *     &lt;enumeration value="F223"/>
 *     &lt;enumeration value="F224"/>
 *     &lt;enumeration value="F225"/>
 *     &lt;enumeration value="F226"/>
 *     &lt;enumeration value="F298"/>
 *     &lt;enumeration value="F299"/>
 *     &lt;enumeration value="I900"/>
 *     &lt;enumeration value="I905"/>
 *     &lt;enumeration value="I906"/>
 *     &lt;enumeration value="I907"/>
 *     &lt;enumeration value="I908"/>
 *     &lt;enumeration value="I910"/>
 *     &lt;enumeration value="I912"/>
 *     &lt;enumeration value="I913"/>
 *     &lt;enumeration value="I914"/>
 *     &lt;enumeration value="I915"/>
 *     &lt;enumeration value="I916"/>
 *     &lt;enumeration value="I921"/>
 *     &lt;enumeration value="I922"/>
 *     &lt;enumeration value="I923"/>
 *     &lt;enumeration value="I924"/>
 *     &lt;enumeration value="T001"/>
 *     &lt;enumeration value="T002"/>
 *     &lt;enumeration value="T003"/>
 *     &lt;enumeration value="T005"/>
 *     &lt;enumeration value="T006"/>
 *     &lt;enumeration value="T007"/>
 *     &lt;enumeration value="T008"/>
 *     &lt;enumeration value="T009"/>
 *     &lt;enumeration value="T010"/>
 *     &lt;enumeration value="T011"/>
 *     &lt;enumeration value="T019"/>
 *     &lt;enumeration value="T024"/>
 *     &lt;enumeration value="T025"/>
 *     &lt;enumeration value="T026"/>
 *     &lt;enumeration value="T027"/>
 *     &lt;enumeration value="T028"/>
 *     &lt;enumeration value="T029"/>
 *     &lt;enumeration value="T030"/>
 *     &lt;enumeration value="T031"/>
 *     &lt;enumeration value="T032"/>
 *     &lt;enumeration value="T033"/>
 *     &lt;enumeration value="T035"/>
 *     &lt;enumeration value="T036"/>
 *     &lt;enumeration value="T037"/>
 *     &lt;enumeration value="T038"/>
 *     &lt;enumeration value="T039"/>
 *     &lt;enumeration value="T040"/>
 *     &lt;enumeration value="T041"/>
 *     &lt;enumeration value="T042"/>
 *     &lt;enumeration value="T047"/>
 *     &lt;enumeration value="T048"/>
 *     &lt;enumeration value="T049"/>
 *     &lt;enumeration value="T050"/>
 *     &lt;enumeration value="T060"/>
 *     &lt;enumeration value="T061"/>
 *     &lt;enumeration value="T062"/>
 *     &lt;enumeration value="T065"/>
 *     &lt;enumeration value="T066"/>
 *     &lt;enumeration value="T067"/>
 *     &lt;enumeration value="T068"/>
 *     &lt;enumeration value="T069"/>
 *     &lt;enumeration value="T070"/>
 *     &lt;enumeration value="T071"/>
 *     &lt;enumeration value="T072"/>
 *     &lt;enumeration value="T073"/>
 *     &lt;enumeration value="T074"/>
 *     &lt;enumeration value="T075"/>
 *     &lt;enumeration value="T076"/>
 *     &lt;enumeration value="T077"/>
 *     &lt;enumeration value="T078"/>
 *     &lt;enumeration value="T079"/>
 *     &lt;enumeration value="T080"/>
 *     &lt;enumeration value="T081"/>
 *     &lt;enumeration value="T090"/>
 *     &lt;enumeration value="T091"/>
 *     &lt;enumeration value="T094"/>
 *     &lt;enumeration value="T095"/>
 *     &lt;enumeration value="T096"/>
 *     &lt;enumeration value="T097"/>
 *     &lt;enumeration value="T098"/>
 *     &lt;enumeration value="T099"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoAnomalia")
@XmlEnum
public enum TipoAnomalia {

    @XmlEnumValue("A100")
    A_100("A100"),
    @XmlEnumValue("A101")
    A_101("A101"),
    @XmlEnumValue("A102")
    A_102("A102"),
    @XmlEnumValue("A103")
    A_103("A103"),
    @XmlEnumValue("A104")
    A_104("A104"),
    @XmlEnumValue("A105")
    A_105("A105"),
    @XmlEnumValue("A107")
    A_107("A107"),
    @XmlEnumValue("A108")
    A_108("A108"),
    @XmlEnumValue("A110")
    A_110("A110"),
    @XmlEnumValue("A111")
    A_111("A111"),
    @XmlEnumValue("A112")
    A_112("A112"),
    @XmlEnumValue("A115")
    A_115("A115"),
    @XmlEnumValue("A116")
    A_116("A116"),
    @XmlEnumValue("A117")
    A_117("A117"),
    @XmlEnumValue("A118")
    A_118("A118"),
    @XmlEnumValue("A119")
    A_119("A119"),
    @XmlEnumValue("A120")
    A_120("A120"),
    @XmlEnumValue("A121")
    A_121("A121"),
    @XmlEnumValue("A199")
    A_199("A199"),
    @XmlEnumValue("F200")
    F_200("F200"),
    @XmlEnumValue("F201")
    F_201("F201"),
    @XmlEnumValue("F202")
    F_202("F202"),
    @XmlEnumValue("F203")
    F_203("F203"),
    @XmlEnumValue("F204")
    F_204("F204"),
    @XmlEnumValue("F205")
    F_205("F205"),
    @XmlEnumValue("F206")
    F_206("F206"),
    @XmlEnumValue("F207")
    F_207("F207"),
    @XmlEnumValue("F208")
    F_208("F208"),
    @XmlEnumValue("F209")
    F_209("F209"),
    @XmlEnumValue("F210")
    F_210("F210"),
    @XmlEnumValue("F211")
    F_211("F211"),
    @XmlEnumValue("F212")
    F_212("F212"),
    @XmlEnumValue("F213")
    F_213("F213"),
    @XmlEnumValue("F214")
    F_214("F214"),
    @XmlEnumValue("F215")
    F_215("F215"),
    @XmlEnumValue("F216")
    F_216("F216"),
    @XmlEnumValue("F217")
    F_217("F217"),
    @XmlEnumValue("F218")
    F_218("F218"),
    @XmlEnumValue("F219")
    F_219("F219"),
    @XmlEnumValue("F220")
    F_220("F220"),
    @XmlEnumValue("F221")
    F_221("F221"),
    @XmlEnumValue("F222")
    F_222("F222"),
    @XmlEnumValue("F223")
    F_223("F223"),
    @XmlEnumValue("F224")
    F_224("F224"),
    @XmlEnumValue("F225")
    F_225("F225"),
    @XmlEnumValue("F226")
    F_226("F226"),
    @XmlEnumValue("F298")
    F_298("F298"),
    @XmlEnumValue("F299")
    F_299("F299"),
    @XmlEnumValue("I900")
    I_900("I900"),
    @XmlEnumValue("I905")
    I_905("I905"),
    @XmlEnumValue("I906")
    I_906("I906"),
    @XmlEnumValue("I907")
    I_907("I907"),
    @XmlEnumValue("I908")
    I_908("I908"),
    @XmlEnumValue("I910")
    I_910("I910"),
    @XmlEnumValue("I912")
    I_912("I912"),
    @XmlEnumValue("I913")
    I_913("I913"),
    @XmlEnumValue("I914")
    I_914("I914"),
    @XmlEnumValue("I915")
    I_915("I915"),
    @XmlEnumValue("I916")
    I_916("I916"),
    @XmlEnumValue("I921")
    I_921("I921"),
    @XmlEnumValue("I922")
    I_922("I922"),
    @XmlEnumValue("I923")
    I_923("I923"),
    @XmlEnumValue("I924")
    I_924("I924"),
    @XmlEnumValue("T001")
    T_001("T001"),
    @XmlEnumValue("T002")
    T_002("T002"),
    @XmlEnumValue("T003")
    T_003("T003"),
    @XmlEnumValue("T005")
    T_005("T005"),
    @XmlEnumValue("T006")
    T_006("T006"),
    @XmlEnumValue("T007")
    T_007("T007"),
    @XmlEnumValue("T008")
    T_008("T008"),
    @XmlEnumValue("T009")
    T_009("T009"),
    @XmlEnumValue("T010")
    T_010("T010"),
    @XmlEnumValue("T011")
    T_011("T011"),
    @XmlEnumValue("T019")
    T_019("T019"),
    @XmlEnumValue("T024")
    T_024("T024"),
    @XmlEnumValue("T025")
    T_025("T025"),
    @XmlEnumValue("T026")
    T_026("T026"),
    @XmlEnumValue("T027")
    T_027("T027"),
    @XmlEnumValue("T028")
    T_028("T028"),
    @XmlEnumValue("T029")
    T_029("T029"),
    @XmlEnumValue("T030")
    T_030("T030"),
    @XmlEnumValue("T031")
    T_031("T031"),
    @XmlEnumValue("T032")
    T_032("T032"),
    @XmlEnumValue("T033")
    T_033("T033"),
    @XmlEnumValue("T035")
    T_035("T035"),
    @XmlEnumValue("T036")
    T_036("T036"),
    @XmlEnumValue("T037")
    T_037("T037"),
    @XmlEnumValue("T038")
    T_038("T038"),
    @XmlEnumValue("T039")
    T_039("T039"),
    @XmlEnumValue("T040")
    T_040("T040"),
    @XmlEnumValue("T041")
    T_041("T041"),
    @XmlEnumValue("T042")
    T_042("T042"),
    @XmlEnumValue("T047")
    T_047("T047"),
    @XmlEnumValue("T048")
    T_048("T048"),
    @XmlEnumValue("T049")
    T_049("T049"),
    @XmlEnumValue("T050")
    T_050("T050"),
    @XmlEnumValue("T060")
    T_060("T060"),
    @XmlEnumValue("T061")
    T_061("T061"),
    @XmlEnumValue("T062")
    T_062("T062"),
    @XmlEnumValue("T065")
    T_065("T065"),
    @XmlEnumValue("T066")
    T_066("T066"),
    @XmlEnumValue("T067")
    T_067("T067"),
    @XmlEnumValue("T068")
    T_068("T068"),
    @XmlEnumValue("T069")
    T_069("T069"),
    @XmlEnumValue("T070")
    T_070("T070"),
    @XmlEnumValue("T071")
    T_071("T071"),
    @XmlEnumValue("T072")
    T_072("T072"),
    @XmlEnumValue("T073")
    T_073("T073"),
    @XmlEnumValue("T074")
    T_074("T074"),
    @XmlEnumValue("T075")
    T_075("T075"),
    @XmlEnumValue("T076")
    T_076("T076"),
    @XmlEnumValue("T077")
    T_077("T077"),
    @XmlEnumValue("T078")
    T_078("T078"),
    @XmlEnumValue("T079")
    T_079("T079"),
    @XmlEnumValue("T080")
    T_080("T080"),
    @XmlEnumValue("T081")
    T_081("T081"),
    @XmlEnumValue("T090")
    T_090("T090"),
    @XmlEnumValue("T091")
    T_091("T091"),
    @XmlEnumValue("T094")
    T_094("T094"),
    @XmlEnumValue("T095")
    T_095("T095"),
    @XmlEnumValue("T096")
    T_096("T096"),
    @XmlEnumValue("T097")
    T_097("T097"),
    @XmlEnumValue("T098")
    T_098("T098"),
    @XmlEnumValue("T099")
    T_099("T099");
    private final String value;

    TipoAnomalia(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoAnomalia fromValue(String v) {
        for (TipoAnomalia c: TipoAnomalia.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
