//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TiposEquipoMedida.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TiposEquipoMedida">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="L01"/>
 *     &lt;enumeration value="L02"/>
 *     &lt;enumeration value="L03"/>
 *     &lt;enumeration value="L04"/>
 *     &lt;enumeration value="L05"/>
 *     &lt;enumeration value="L06"/>
 *     &lt;enumeration value="L07"/>
 *     &lt;enumeration value="L08"/>
 *     &lt;enumeration value="L09"/>
 *     &lt;enumeration value="L10"/>
 *     &lt;enumeration value="R00"/>
 *     &lt;enumeration value="R01"/>
 *     &lt;enumeration value="R02"/>
 *     &lt;enumeration value="R03"/>
 *     &lt;enumeration value="R04"/>
 *     &lt;enumeration value="R05"/>
 *     &lt;enumeration value="R06"/>
 *     &lt;enumeration value="R07"/>
 *     &lt;enumeration value="L00"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TiposEquipoMedida")
@XmlEnum
public enum TiposEquipoMedida {

    @XmlEnumValue("L01")
    L_01("L01"),
    @XmlEnumValue("L02")
    L_02("L02"),
    @XmlEnumValue("L03")
    L_03("L03"),
    @XmlEnumValue("L04")
    L_04("L04"),
    @XmlEnumValue("L05")
    L_05("L05"),
    @XmlEnumValue("L06")
    L_06("L06"),
    @XmlEnumValue("L07")
    L_07("L07"),
    @XmlEnumValue("L08")
    L_08("L08"),
    @XmlEnumValue("L09")
    L_09("L09"),
    @XmlEnumValue("L10")
    L_10("L10"),
    @XmlEnumValue("R00")
    R_00("R00"),
    @XmlEnumValue("R01")
    R_01("R01"),
    @XmlEnumValue("R02")
    R_02("R02"),
    @XmlEnumValue("R03")
    R_03("R03"),
    @XmlEnumValue("R04")
    R_04("R04"),
    @XmlEnumValue("R05")
    R_05("R05"),
    @XmlEnumValue("R06")
    R_06("R06"),
    @XmlEnumValue("R07")
    R_07("R07"),
    @XmlEnumValue("L00")
    L_00("L00");
    private final String value;

    TiposEquipoMedida(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TiposEquipoMedida fromValue(String v) {
        for (TiposEquipoMedida c: TiposEquipoMedida.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
