//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:20:41 AM CEST 
//


package com.eon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoVia.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoVia">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="AR"/>
 *     &lt;enumeration value="AU"/>
 *     &lt;enumeration value="AV"/>
 *     &lt;enumeration value="BC"/>
 *     &lt;enumeration value="BD"/>
 *     &lt;enumeration value="BL"/>
 *     &lt;enumeration value="BO"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CF"/>
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="CM"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="CS"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="DI"/>
 *     &lt;enumeration value="ED"/>
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="FC"/>
 *     &lt;enumeration value="FI"/>
 *     &lt;enumeration value="GL"/>
 *     &lt;enumeration value="GR"/>
 *     &lt;enumeration value="MA"/>
 *     &lt;enumeration value="MU"/>
 *     &lt;enumeration value="MZ"/>
 *     &lt;enumeration value="NU"/>
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="PB"/>
 *     &lt;enumeration value="PD"/>
 *     &lt;enumeration value="PE"/>
 *     &lt;enumeration value="PI"/>
 *     &lt;enumeration value="PJ"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="PO"/>
 *     &lt;enumeration value="PQ"/>
 *     &lt;enumeration value="PR"/>
 *     &lt;enumeration value="PS"/>
 *     &lt;enumeration value="PT"/>
 *     &lt;enumeration value="PY"/>
 *     &lt;enumeration value="PZ"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="RD"/>
 *     &lt;enumeration value="RS"/>
 *     &lt;enumeration value="SD"/>
 *     &lt;enumeration value="TR"/>
 *     &lt;enumeration value="UR"/>
 *     &lt;enumeration value="VI"/>
 *     &lt;enumeration value="ZN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoVia")
@XmlEnum
public enum TipoVia {

    AC,
    AF,
    AG,
    AL,
    AR,
    AU,
    AV,
    BC,
    BD,
    BL,
    BO,
    CA,
    CF,
    CI,
    CL,
    CM,
    CN,
    CO,
    CR,
    CS,
    CT,
    DI,
    ED,
    EN,
    FC,
    FI,
    GL,
    GR,
    MA,
    MU,
    MZ,
    NU,
    PA,
    PB,
    PD,
    PE,
    PI,
    PJ,
    PL,
    PO,
    PQ,
    PR,
    PS,
    PT,
    PY,
    PZ,
    RA,
    RD,
    RS,
    SD,
    TR,
    UR,
    VI,
    ZN;

    public String value() {
        return name();
    }

    public static TipoVia fromValue(String v) {
        return valueOf(v);
    }

}
